/*
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWNNNNNNWWWNNWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWNNNNNNNNWWNNNNWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNWWWWWWNNNNWWWWWWWWWNNWWNWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNWWNWNNNNWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWNWWWWNNWWWWWNNWWWWNNNNNNNNNNNNNNNNNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNWNNWNNWNNNNNNNXXXKKK00000000000KKXXXXNNNWWWWWWWWWWWWWNXKK0OOkkkkkO0KXNNNWNWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWNNNNNNWNNXK0kxddolccc:;;,;;;;;,;;;;;:clodxO0KKKKKXXNNNXKOkxdlcc::;;,,;:cloxO0XNNWWWNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNKOxoc::::cccccccccccllllccllllllllooddxxxxxxxxkkxxxdoddoooooooolcc:;,,;:cldk0XNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXko;,,;:cllllllllooooooooooooooooodddoooooodooooodoooooooooooodoooddddooolllc:::cldOKXNNNNWNNNNNWWNNNNNWNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWNNXx:'';cclllllcllooollooooolllllloollllllllllllloollloooooooooollooooooooooooddooolc;,,;coxOKNNNWNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNWWNX0o;';ccllccllllllccllllollloollllooollllooooollllolooloooooooooolooooooooooooooodddollc:;,,,:lxOKXNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNX0kxol::cccclccccllllllllllloooooooollllllllooooooooooooollooolloooooollloollooooooooooooloolllc::;;:ldk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNN0d:;;cllcccllllllccllllllollooooooooooolooollooloollllllloooooolloolllooooloooolooooooolllllooloooooolccccloxkOOO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWXk;'';:cclccclllllllllllooooloolloooloooooooooooooooolllllooooooooolloooolloooooooloooooooooollloooooooooooooooolccloxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNWWNWXx,.,clcclcccllllllllooolloollloolloooooooolooooooooolllllloooolooooloooooollloooloolllooooloolloooooooooodooooddoollllclxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWNNNO;.,:ccclllccllllooooooollooooloolloooooooloooooooooooollllloooooolloooooolooooooooollllloolloooooooooooooooooooooooooollcclx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNKl'':llllllollollllloolooooooooooooooooooooooooooooloolloooooooooolloooooooooolooooooolllllloooolooooooollloloooooooooooooolccclkXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNNNNWNO:';cloooloolooooolooooollllloooloooooooooooooloooollollooooooooooooolloooooooolooooollllloolooooooooololloooollooooooooodooooc::lkKNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNWNNWNXx,':loooooooooooooooooooooollooooooooooooddoooooooooooollooooooolooodooooollooolooooolllloollloooooloolooloooollllllooooooooooooc::lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNWWNNNNWNNNNKl',clooooooooooloooloooooooooooooooooooooooooooooooooooooooooodoooooooooooooolloooooolllllllloolooolooooooooloooolloooooooooooooolc::oOXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNN0c.,clooooooloooolooooooloooooooooloooooooooodolooooooooooooolooooooooooooooooolloooooollllloolllooolloolloooooooooloollllllloooooool:;:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNXKKK0KKXNNNWNNO;.;loooooooooooooolooolooooooodoooooooodddooodoodooooooloooooooooooooooooooooooooooolooooloolllloollolllllolloooooollolllooooooooooool:;ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNNNNNNNXKOxoc:;::clldkKXXKd,.;looooooooolllllooooooooooddddddddodddddooodddddddoooooooooooooooooooolooooooooooooooooooooollllllollooooooolloollloooloollllllooooolc;:o0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNNX0xo:;,,,;:::c::::coxkko,.;loooooloooollooooooooooooooddddddoodddddoodddddddddddddddddoooooooooooooooooooooooooooooooolllllllllllolooolooollooollllllllllloooollc:;ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNN0xc;',;::ccclllllllllllodl,.,coooooooooooooooooooodoooodoooddodddddddodddddddddodddddoooooddddooooolooooooooooooolooooollllllllllllloolllooollollllllllolllllloooool:;:dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0o;',;:clllllllllllllllllllc,.'coooooooooooooooooodddddooooooodddddddddddddddooddddddddooooododddodoooooolooooooooooooolllooollllollloooolloolloolllllllollllolooloooolc;;o0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNXx:,;:cllllllllooollolllllllol:'.,loddooooooooooooooolcc::;;;;;::clooodddddddddddddddddddoooooooodddddddddoooooooooooloooooollllloolloollollloolloooolllllolllooollllooolll;,:kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNKxlcclllllollllllllloooloooooool:'';loooddoooooolc:;,'''''',,,,,,,,;;:clodddddddddddddooodddooooooooooodddddddoooooooolloooooooloooooooollloooooollooollollllooollloolllloool:;;o0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNX0xolllllllllooollloooooloooooooooo:,;:lodddooool:'''',;:clloooooooolllcclloooodddddddddddddooooooolloooodddddddooooooodooooooollooolloooollooooollooollllollllloollllollloooool:;;lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXkooolllloooooooooooooooooooollooooollccloddoooolc,,;coodddoooooooooooooooolc::cloddoddooddddoodooooooooooooodddddddoooooooooooooooollloooooooooollloolollllllllloolllllllllllloolc;,:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXOocclolloooooooooolollllloooolloooooooooooddoooooolloddollcccccllloooooooooolc:;:coooooooddddooolooooooooodoooooddddddooooooooooooooolllooooolooloololloollloloolllooooollllllollllc;,:d0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKko:;cllllooooolloooooooollloolooloooodoooooodoooooooollc:::::cccllllooooooooooool:;;cooolooooooooooooooolloooddoooodoodoooloooooooooooloooloooooooooooooooollloolllooolollollllllloolc;,;o0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xl:;:looooooooolooooooooooooolllllooooooooddoooooooolc:::cllollooooooooooloooddooooc:;:llloooooooooooooooolloooddooooodddoooooooooooooolooolooooloolooooooooooloolllllolllllllllllloooll:;:okKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xl:;:loooooooooooooooooooooddoolloooooooooddddoooooc:;:clooooolloooooooooooooooooddool:,;clllloooooooooooollloooooodooooddoddooooooooooooooooooolloooooloooooooooolllllolloollllllllllllllccccoOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0dl:,;looooooooooolloooooooooooooooooooooooooooodool;;:cooooollllllllccccc::clloooooooooc;';cllllllooololllloolooolodddooooooddooooooooooooloooooooooooooooloooooloooollllllllllllllllooollolollclxKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxl;,;loodoooooooooooooolooolooooodoodolooooooooodo:,,:oddollllcc:;,,'''''',,;clooodoooodo:,,:llllllllloooollloollloooodooooooooooddoooooddooooooooooooooooollllooloolollllolooooollllollloooloolllld0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl;,;cooooollllool:;,,,,,,,;;:cclloodoooooooodoodo;',cooddolc;,''.',,;:cclllllloooooodddddo;';clollllllllloololllllooooodddoooolc:clooooodoooooooolooooooloooooooooollolloooolllllloloolllllllooooolcoOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0o,';loooolcccllooc:;;;;;;,,,''.'',;:cooodoooodool;',coddol:,''',:ccccc:;;;,,,,',;cooodddooo;',:lolllllllllollllllllloolloooooool:,'coooooooooooooooooooooooooooloooooooolloooolllllloollllllooooooollcoOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKo,';looooc:;:loooooooddoooooollc:;,'.',:loooooodl;';lddoc;,,;:cllc:,'''.'',;;:;;;:coooddddol:..:lollcllllloolllllllllll::loodddool;',:loooddoooooooooooooooooooooooooolooooolllllllllloolllooolllllloolco0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo'.;loodoc;;:loooddooddoooddddddddoll:;'.';codool:,:odoc;:coxxdoc,''',;:cclooddddddddooodddoo:'.;loll:;:llllooolllloollc:;clooodddol;',coooddooooodoooooooooooloooooollllooooloooooooolooooolllolllllooolco0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,.;lloooc,,:oddddddddddddoooolccclllloolc,'';ldoc:lxkkdoxOKKXXKx::ldddoolccc::::::::::codddooc'.;clll:,;cllllooollllloll:;:clooodoolc;',:llooooooodooooooolooooooooooolloooooodoooooooooolllllllollllooolccdKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMM
 * MMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.;loool:''coddddddoddool::;,,''''',,;:loddc,',ldxk0KXXXXNNNNNNNX0KXKxl;,,,,;,;::::;;,'',:loooc,.,clllc;,;clllloolllllolll:;:cloooooool:'';cooddddooooooooollllooooooooooooooooooooooooooooloolllllllooooolcckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMM
 * MMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;';loool:'':oddodddool:;'''',;:ccccccccccldxxdlcoOKXNNNNNNNNNNNNNNNNNKkooxkO0KKKK0xolclloooooool;.,:llll:,';cllllooolllollll:;:cloooooooo:,',cododoooooooooooolllllcloooooooooooooooooooooooooolllllllolooooc:lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMM
 * MMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNO:.;loool;'':oddoooolc;'',;:llodddddooddddxk0KXXX00XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOkkkO0KK0kddol;..;clool:,';cllllooollllloolc;;:looooooooc;'';cooooooooooooooolllc;:cloooooooddooooooooooooodoollloollllooolc:dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMM
 * MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl',coool:'':odooooll:;::looododdddddooodk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxdo:'.;clolll:,';clloooooollllooll:;:clooooooooc,'';coooooooooooolloll:,,:lodooodoollooooooodooooooooolllllllodol;ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMM
 * MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,':looo:'.;looooooolllooooooddoolccccldOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOkxdl,.,;collllc,'':cllooolllllllolc:;;:loooooddolc,'';clooooddddoooooll:,',:loooooolooooooodoooooodooooloollloddl;;dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMM
 * MMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKc',coooc,.,cllooooodooooddoodol:;;;cldOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOxddc,,,:lllllll:'',:looooloolloollll:;;cloooddddooc,'',:looddddoodddoooc:,',:cloooooooooooooollooooooooooolloodl;'c0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMM
 * MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk,':lodl;.'coolloooodoooooolc:;,;:ldx0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kddo:,',:lllllllc;'';cllloooolollooolc;,;clooddoooolc;''';clododdddooooool:,'';clooooloooooooooooooooooooooooodo:';kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMM
 * MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd'':loo:..;looooooooooooooc,'':lodddkKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kxdo:;,,:lloollolc;'';cloooooollloooll:;,;coddddolcccc:;'',:clooodoooooooooc;'',:coooooooooooollooloooooooooloo:.,dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMM
 * MMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo''cll:'.,coooooooooooooc;'':lodocclkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kkxol:'';cllllloolc,'',:looooollloooooc;'';loodddlc:clll:;'',;:coooooooddddol;,'':cloooooooooolloloooolloooloo:''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMM
 * MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0l,:lol,.'coooloolcoooolc,.,coooc;;oOXNNNNNNNNNNNNNNNNNNNK0OOKXNXKOkO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kxxdoc,',:lllllllll:;''';cooolllllooool:,'':looddolc:cclllc;,'',;clooodddddool:;'',cllooloooooooooooooooloool:''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM
 * MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXklcloo:..;loooolc:clool:'.;lool;,;dKNNNNNNNNNNNNNX0OO00KK0koccox0Odc;:okKNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0Okxxdl:'',:lllllloool:,'',:loooollooddol:,',:lodddoolc:cloooc:,,'',:cloddooooooc;'',:llllloooooooooddooooloo:.'cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
 * MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKxllooc,.,coolol::cllol:'.;lool;':xKNNNNNNXK0O00K0xl:;;;:cldxxol:cdkOko:;lxKNNNNNNNNNNNNNNNNNNNNNNNNNNNKkdlllddl;'',,,,;clllccc:;'',;cooooooooooooc,',:loddddolcc:cldddlc:;,'',;:codoooool:,'';clllooooooooooooollol;.,lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
 * MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOolooo;..;looll:;:lllol;',cooc,'cOXNNXXXXKkdc:;::::::loddoc:;:ldxoccok0Od:;lOXNNNNNNNNNWNNNNNNNNNNNNNKOdlccloxxl;,'...',;,,'',;clc:,'',:looooloooool:'.';lodddddolc:clddodolc:;,''',:loooool:,'';cllooooooloodoololc;.,lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
 * MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkooddc,.,coollc;;cooolc,':ooc,'cOX0xocc:cccccloxxdoc:;;:lxOOkoccoxOkdodO0Oo;:dKNNNNNNNNNNNNNNNNNNNX0xlcoxxxdl:;:cc:,......,;:::::;,,,,,,,;cooooooooooc,'.',:loddddol:::lodddddool:;,'',;cllool:,.';clooooollodoooooc,.;d0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
 * MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkoloo:'.;loooc;,:lool::cclc:,':kXXOdllooooolclldk0XXKOxoc:cd0XKOxxOXXKOO0KKx:;o0XNNNNNNNNNNNNNNNX0xlcoxdl:::cllc:;,;clc;'.''''''''''',;,'.';cloddooloolc:,..,;loddddoc:;:loddddoodool:,''',:lool;'.':looodooooooooo:'.:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxllol:.':llol:,,codo:;coo:'..,d00kddooddddxkkO000KXNNNNNX0OOKNNNNXNNNNNNXNNXkccxKNNNNNNNNNNNNNNKxooxOOo:cxk00x:;cdkKKOo;'',,'..',,'...',,,,,;ccllllooolccc:;'.';codoodoc:;:loddoooododolc;,',:lllc,.':loooooooooool;.,lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkoooc,.,loolc,,:odo:,:oo:'..'lkd:;;::ccc:::loxKNNNNNNNNNNNNNNNNNWNNNNNNNNNNNXKOKNNNNNNNNNNNNNNKxoxKXX0kOKNNNXK0KXNNNKxccdO0kl,'',''..',,,,,'''',,,;loooc:::::;,'',:odddooc;;;coddoodoodddolc;,;:loc;'';cooooooooooc,.;dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xdoc'.,loll;';looc,,col'...:kK0O0KKXXXXXKKKKXNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX00XNNNNNNNNNNNNNNNNNNNXXXNNNX0kOOOko:;;:ccccc::cccccllooolc:;,;::;'',codddolc;,;loddddooolloool:::lol:'.,coooooc:cl:''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkdo:'.;lol:''cool:,;lo;...'l0NNNNNNNNNNNNNNNNNNNNNXXKXXKXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0O00KKKkl;,,,,,,''',:clll:;,,;:;,,;:codddoc;,;codddoc,;coddolcclol:'.,looll;,;:,.:ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxo:'.;llc'.,lool;':ol,...'cdddddddxxdddddoollllllc:::::::::::::::::cllodkOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXNNNNNNNNNNNNNNNNNNNNNNNXXKXXKOkkxdolllc:;;::;:cc:;,,;;,,',;codddl:,';coddl;'':oddooooool;.';lllc;',;',xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0dc'.;ll;..:lool:,:o:'''..',;:::::::ccccccccccllooodxxxxxxxxdxxxxdooolc:;;cx0XNNNNNNNNNNNNNNNNNX0xollllcccccllooooloooooddxxxxxxkkOOOOO0KKXNNNXK0Okxdolc:;,,;;;;,,;cc:;,;coddol;'':lool;'':looooooooc,.,clc:'.,:cxXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl'.;lc'.,cloodl;;,'.','.,o0XXXXKKK000OOOOOOO00KXXXXXXXKKKKXXNNWWWWWWNXOo;,lONNNNNNNNNNNNNNNKkl;;:cclllllllllllllllcc:::;;,,,,;;;;,,,;;:cldk0KXXKOxddolllc:;''',;cooooc,,;loddoc,';codo:'';lddoooool,.':cc,.'cx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx;':l:..;llodoc,','.,;'.c0WWWKxl::;;;,,,,,,,,,;;:::::;;,,;;:cllokKNWWWWXx;,o0NNNNNNNNNNNNNKo,;d0XXXXXXXXXXKKKKKKK0000OOkkkkkkOOOOOkkxdol:;,;cd0KOxolc;;:ccc:,'.,:loddol:',:loddl;',:odoc,';loddoooc,.';c;..:OXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo:cl;.'clodl;';dxc',:,.cOWWNk;.................................':xKWWWWKo,:kXNNNNNNNNNNNXd,;xKKkoccccccc::;;;;;;;;;;;;;;;;;:ccloxk0KXNNX0ko;,cdl;,''......'''',;coooodoc,';coddl;'':oooc,.;lddool:..,::'.;kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxoc,.,codl,'cOX0l',lc,;dXWNk;...................................,o0NWWNk;;xXNNNNNNNNNNNOc,o0Oc'.................................',;cdOXWWXx:,;ldocccc:,....';clllc::lodl;''codol;'':odo:.':lool:'.'::,.;kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxc'.,ldl,'l0NNKx;,ldc':kNNk;....................................'l0WMW0ook0OxooooodxkOd;,dKk;......................................':kXWWXd,,d0Oxollll:;'.,:looo:,';lool;'':lool;.,looc,.,col:'.,::,.;kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl,.,ll;':ONNNNKd:;cc,'c0Nk;.....................................;kNWWNOo:;;;:ccccc:;;,',dKO:.......................................'l0WWKo',okxo:;,;ccc;'.,coddl:,.;lool:'';ldoc'.:ool;.':llc::c:,.,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkc',cc',dKNNNNNXOdll:,;xX0c.....................................;xNWNOl;cdOKKXXXXK0Od:,,oKKo'.......................................;xNNOc'';:;,'.....''..',cdddoc'.;lool:'':lol,.;ldo;.':oolclc,.,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0l,''':ONNNNNNKOxol:',oXXd,....................................:OWNk:;dKNNNNNNNNNNNXOc,lKXx;.......................................,dXXd,':l:;,,,,'..'',,',codddo:''coool;.,coc,.;loc,.,ldoolc,.,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo,.':OXNNX0dc,',:c;'c0N0l'..................................;xXWXd,;xXNNNNNNNNNNNN0l,l0NO:.......................................,xXOc':kx:'.............'',;col,';oddo:'':l;.':l:'..,ldool;.,xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:.':dxdc,',cdOK0l';xNNk;.................................;xXWWKl':kXNNNNNNNNNNNNKo,cONXd,.....................................'cO0o';dKOl:;;;;,'':oddddl:;,'','.,lxdo:',c:,;c:,'...;lool;':kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,';:,.':oOXNNNXk;,oKWXd;...............................:kNWWXx;,oKNNNNNNNNNNNNNXx;:kNNO:.....................................;xKd,,oKNKOxl;,:lox0XNNNNNX0Odc,..':odoc:loooool:,..':clooldKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0l,''';d0NNNNNNNO:.:ONWXx:'...........................,l0NWWXx;,lOXNNNNNNNNNNNNNNO:,oKWXd,...................................,d0k;'c0NNKOdc,.'ckXNNNNNNNNNNNXOo:'.':ldxddxdol;'...,;;:d0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,.'lOXNNNNNNNNKd;,l0NWNOl,........................,lONWWN0o,,l0XNNNNNNNNNNNNNNNKo,:ONW0l'.................................,oOx;'cOXNNX0x:',:x0NNNNNNNNNNNNNNX0d;..;odlc:;,'',;,',:;;lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo,.;xKNNNNNNNNNNNXx:,cxKNNKxc,'...................,lONWWWXx;':xKNNNNNNNNNNNNNNNNNXk:,l0WN0o,..............................,lkOo,,l0NNNNNXKOookXNNNNNNNNNNNNNNNNNXkc'.',,'.',cll:'':l;,cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo,.:kXNNNNNNNNNNNNNXOo:;cd0XNX0xl;,''.........',:ld0NWWWWKo,,lOXNNNNNNNNNNNNNNNNNNNXx;,oKNWXOl:;'.......................';oOXOc';dKNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNOl,.',,';ldo:'';c:,,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.;xXNNNNNNNNNNNNNNNNXOo:,;lx0KXXK0OkxdoooooxkOKXNWWWWX0d:,;o0NNNNNNNNNNNNNNNNNNNNNNKx:;lONWWNXKkoc;''................;okKX0d;':kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0l'..'':oo:'.,::''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0c.'oKNNNNNNNNNNNNNNNNNNNXKxl;,,;cldxkO00KK0KKKKKKKK0Oxo:;,:d0XNNNNNNNNNNNNNNNNNNNNNNNNXOdoloxKXNNWNXKOkdoc::;;;,,,,;:ld0XKko;,:d0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk:...':l:'.';;''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.:kNNNNNNNNNNNNNNNNNNNNNNNX0kxol:;;;,;;;;,;;;;;;;;,,,:cdOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0xc;;cloxkO0KKKK0OOOOkkxxxxxxxoc;,;cx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXd,..,::'.';,.,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo''lKNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0Okxdddddddddddxxk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkdllc:;;;:::::::;;::::;;;;;clox0XNNWNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNN0c..,;'..''';xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo''oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0OOkkkkkkkkkkkkkkO00KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0l'.','...,lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd,'cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO:.':c,',lkXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0c',o0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXd,.;odox0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0c',lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNX0Okkkxdl:;,'',,:ldxOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXx;.,dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKo,'ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk:,,'''',:coxxdl:,'',;coxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk;.'oKNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd,.:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0kxxxxxO0KXNNNNXKOxdl:,'':kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKd;.,oKNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:',:ok0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kxx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNKxc'.:xXNWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxl;'';cdk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOo:'';o0NWWWNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
 * MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWNKkoc,',;coxk0KXNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNXKOkdl:'.,cxKNNNNWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
 * MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWNX0xoc;''',:coxO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kxxdooolllooooddxxxkkkkxxxddoooollc;''',:ldOXNWWWNWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
 * MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNWWNWNNXKOxoc;,''',:codxk00KXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kdl:;,',;;:::;;;,,,''''''''''''''''',,,;:cldk0XNNWNWWWNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
 * MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNX0Oxoc:;,''',;:::ccllooddxxxxxxxxxxkO00KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKko:,'',:odkOKKXXXXKKK0OkkkOOkkkkkkkkkOO000KKXNNNWWWWWWWNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM
 * MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXKOkxdolc::;;;,,''''''''''''''',;;;codkO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0dc;,;cdk0XNNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM
 * MMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWNNWWWWNNXXXXKK000Okkkkkxxxxxxxxddlc::;;;;:ldkOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNKxc;cx0XNNWWNNWWNWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMM
 * MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNWWWWNWWWNWWWWWWWNNNWWNWWWNWWWWNWNNXXK0kxdoc:;:lkKXNNNNNNNNNNNNNNNNNNNNNNNXOl,,l0NWWNWWWWNNWWWWWWWWWWWWWWNWWWWWWWNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMM
 * MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWNWWNWWWWWWWWWWWWWWWWWWNNKkl,,cxKNNNNNNNNNNNNNNNNNNNNNXx;',dKNWWNWWWWWWWNWWWWWWWWWNWWWWWWWWWWNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMM
 * MMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:';dKNNNNNNNNNNNNNNNNNNNXx;.;xXWWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMM
 * MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx,.:kXNNNNNNNNNNNNNNNNNNOc.':oxOXWWNWWWWWWWWWNNNNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMM
 * MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0Oxo:'.,dXNNNNNNNNNNNNNNNNNNOc'':c:cd0XNWWWWWWWWNNNNNNWWWWWWWWWWWWNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMM
 * MMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNWNWWWWWWWWNNNXKKKKK00ko:''',;'.,oKNNNNNNNNNNNNNNNNNN0l':kKkc:codxOKXNNNWWWNNNNNNNNWWWWWWWWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMM
 * MMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNNNWNNNNKOkdolc:;,,,,,''''..:kk:.,dKNNNNNNNNNNNNNNNNNNO:'cOOc,ckOo;,;:cldxOKXNNNWWNNWWWWWWNNNNNNNNNNNNNNNNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMM
 * MMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNWWNKkoc;,;:clllc:,..;oxkx:,o0x,.;xXNNNNNNNNNNNNNNNNN0c,:xx:,cONWXOl'..,;;;:lxKNNNNNWWWWWWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMM
 * MMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOo;,;ldOKXNWWWNOc.'oXWNO:,okl'.:OXNNNNNNNNNNNNNNNXk:':xx:,c0NWWNk:.'ckKKOd:;cxKNNNNNWWWNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOo:',cxKWWMMMMMMWWKl''lKWWO:'::'.'cOXNNNNNNNNNNNX0kdl,'cxo;,l0WWWKd;.'l0WWWWN0d:;:dOKNNNNWWNNWNWWNNWWNNWWWWNNWWWWWWWWWWWWWWNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXko;,;cx0NWWMMMMMMMMMWXd'.:OWW0l,,cl:,,:coxxkkkkkkxoc;'.';dxl,;dKWWXkc'.;xKWWMWWMWNKxl;;:d0XNNWWNWNNNWNWWNNNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKkl;,,lkKNWMMMMMMMMMMMMMWNx;.;kNWNk:,o0KOdl:;;;,,,,,,,;::,'':c;,cONWW0l,.,l0NWWWMMWMMMWWN0dc;;lx0XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNX0kl,';lx0NWMWMMMMMMMMMMMMMMMWOc.'oKWWXx;,ckKXNXXK00OOOO000Od,...':xKWWXkc'.:kXWMMMMMMMMMMMWWWNXOo:;;lx00KXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0kxdlc;,';lkKNWMMMMMMMMMMMMMMMMMMMMWXx;.,oKWWXd,.,;codxkkkkkkxdoc:,'',cxKWWXkl,.,l0WWMMMMMMMMMMMMMMMMWWNKOo:,,;;:ccllodxkKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOd:,,,;:coxOKNWMWMMMMMMMMMMMMMMMMMMMMMMWXx;''ckXN0xdxdlc;;,,,,,,;;:lodkO0NWN0d:'.,ckXWMWWMMMMMMMMMMMMMMMMMMWWNKOkxdoollcc:;;:d0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0d:,,:dOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOo,',:oxkOXNNXK00OOO00KXXKkxk00kdc,.';oOXWMMWMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNXKkl;;cxKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd;':dOXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOo:,'.',:loddddddddodoo:''''''.',cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0d:,:xXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:':xXWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXOo;'','''''''''''''''',:ccoxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWKd;,ckXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo,,o0WWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWN0kO00OOOOOOOOOOOkkOOKNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWWN0o;,l0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,,oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMNOdkXWWWMMMMMMMWKxd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOc,:xXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;'lKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,lKWWMMMMMMMW0l;lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0o;,lOXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl':ONWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxlxXWWMMMMMMWNOdxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXOl;;o0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;'dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKk0NWWMWWWWXkokXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXx:,l0NWNWWWWWNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx:l0WWWWWNOc,:xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWNk;,oXWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWN0:'lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx;:kNWWN0o:lxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWKl'c0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNWWWWWNNNWWWWWWWWWWWWWWWWNNNk;,dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKolkXWN0c,oKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXx;,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNWNNNWNNWWWWWWWWWWWWWWWWNNWNO:'oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxcccll:,;xNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOl,,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNWNNNNNNNNNNNNNNNNNNNNNNNN0c'c0WWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0d:',:cclkNWWMMMMMMMMMMMMMMMMMMMWWNWMMMMMMMMMMMWNXNWMMMMMMMMMMMMMMWNNWWMMMMMMMMMWWXOl,,ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNXd;;xKNWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc,';ldkKNWWWMMMMMMMMMMMMMMWMWN0dco0NWWMMMMMWN0dc:dKWWMMMMMMMMWWN0dccxXWMMMMMMMWNkc,;lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNXkc:cdOXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,':l:;dXWWWMMMMMMMMMMMMMWWNOc'..:kNWMMMWNX0d;..,oKNWWWWWWWWNKkl,.,lONWMMMWWWXkl,,o0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNWNNWNNXkl;;lx0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWN0d:'':c,':ox0NWMMMMMMMMMMMWNKx;..'oKNWWNKOdc;'..'',:xXWNX0kdol:;'..:kNWWWWNXKko:,;oONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNWWNNNNNNNNNNNNNNNNNNNX0xc;;cldkKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOdolcc::::clkXWMMMMMMWWWWKxc,....,o0KOoc,..';coxl,.'cdoc;'..',;;,..cOXKOxoc:;,;lxKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNX0xoc;,;cd0NWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNWWMMMMMMWNX0o,..,:;...;:,...;cdOXNNKl'.....':ldxO0KOc..,::;,,;cox0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkd:,;oOXNWWMMMMMMMMMMMMMMMMMMMMMWWMMMWWWWWWWWWWWWWWWWMMWWMWWMMMMWNOl;'..:xK0l'.....;oOKNWMMWXd,..';coxkOOxdlc;'.',:ldk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkl;;:lxO0K0OxdddddddddxxxxxxkkkkxdoolcccccloooooddxkOO0KXXNXX0o,...:d0XX0l'.',cxOKKKKKKKK0d:,,clc;,'',,;:loodkKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xoc;;;;,',;;;;;;;;;;;;;;;;;;;;;:ccllllcccccc::;;;,,,;;:::;,....';;:::;'..',;;;;,,,,,;;;,,',,,,;;:oO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxxk0KKKKKKKKKKKKKKKKKKKKKXNNNNNNNNNNNXXXKK00OkxxxxxxddddooooooooooodddxxddxxdddxxxxkO000KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 *
 */

package net.kunmc.lab.seihekizinrou.commands

import dev.kotx.flylib.command.*
import dev.kotx.flylib.menu.Menu
import dev.kotx.flylib.menu.menus.*
import dev.kotx.flylib.utils.*
import kotlinx.coroutines.*
import net.kunmc.lab.seihekizinrou.*
import net.kunmc.lab.seihekizinrou.utils.*
import net.kyori.adventure.sound.Sound
import net.kyori.adventure.text.format.*
import org.bukkit.*
import org.bukkit.enchantments.*
import org.bukkit.entity.*
import org.bukkit.event.inventory.*
import org.bukkit.inventory.*
import org.bukkit.inventory.meta.*
import org.bukkit.potion.*
import java.awt.Color
import java.util.*
import kotlin.concurrent.*

object StartCommand : Command("start") {
    internal var timer = Timer()
    internal var count = 0

    private val scope = CoroutineScope(Dispatchers.Default)

    var nightMenu: BasicMenu? = null
        private set

    override fun CommandContext.execute() {
        server!!.title(
            "性癖人狼".component(Color.RED, TextDecoration.BOLD),
            "自分の性癖をチャットに入力してください".component(),
            1,
            7,
            1
        )
        SeihekiZinrou.step = SeihekiZinrou.Step.WAITING_INPUT
        timer.cancel()
        timer = Timer()
        SeihekiZinrou.propensities.clear()
        plugin.reloadConfig()
        count = plugin.config.getInt("time_input")

        scope.launch {
            server!!.onlinePlayers.map {
                scope.launch {
                    println("Getting head of ${it.name}")
                    HeadUtil.getHead(server!!, it.name)
                    println("Got ${it.name}!")
                }
            }.joinAll()
        }

        server!!.playSound(
            Sound.sound(
                org.bukkit.Sound.AMBIENT_CAVE.key,
                Sound.Source.MASTER,
                2f,
                .3f
            )
        )
        world!!.animateTime(plugin, 20000, 100)

        runBlocking { delay(2000) }
        timer.scheduleAtFixedRate(1000, 1000) {
            count--

            if (count > 0) {
                val last = server!!.onlinePlayers.size - SeihekiZinrou.propensities.size
                server!!.sendActionBar(text {
                    +"自分の性癖をチャットに入力してください || ${last}人の入力を待機中... || "
                    append(
                        "残り${count}秒", when (count) {
                            in 0..10 -> Color.RED
                            in 10..30 -> Color.ORANGE
                            else -> Color.GREEN
                        }
                    )
                })

                if (last == 0) {
                    scope.launch { start() }
                    cancel()
                }

                return@scheduleAtFixedRate
            }

            scope.launch { start() }
            cancel()
        }
    }

    private suspend fun CommandContext.start() {
        plugin.reloadConfig()
        val werewolfNumber = plugin.config.getInt("werewolf_number")
        SeihekiZinrou.step = SeihekiZinrou.Step.ROLE_ANNOUNCEMENT

        if (werewolfNumber >= SeihekiZinrou.propensities.size) {
            server!!.sendActionBar("参加人数が設定された人狼の数より少ないためゲームを開始出来ませんでした。".component(Color.RED))
            return
        }

        delay(2000)

        title(
            "役職が発表されます...".component(),
            "".component(),
            1,
            3,
            1
        )

        delay(7000)
        SeihekiZinrou.propensities.shuffle()
        SeihekiZinrou.propensities.subList(0, werewolfNumber).forEach { it.werewolf = true }

        server!!.playSound(
            Sound.sound(
                org.bukkit.Sound.AMBIENT_CAVE.key,
                Sound.Source.MASTER,
                2f,
                .3f
            )
        )

        SeihekiZinrou.propensities.forEach {
            it.player.title(
                text {
                    append("あなたは")
                    if (it.werewolf)
                        bold("人狼", Color.RED)
                    else
                        bold("村人", Color.GREEN)
                    append("です")
                },
                text {
                    append(if (it.werewolf) "人狼であるとバレないよう立ち回り、誰を処刑するか話し合ってください。" else "性癖を元に人狼を推測し、なるべく早く処刑してください。")
                },
                1,
                7,
                1
            )
        }

        delay(5000)

        val wolves = SeihekiZinrou.propensities.filter { it.werewolf }
        if (wolves.size > 1) wolves.forEach { wolf ->
            wolf.player.send {
                bold("--- ", Color.GRAY)
                bold("自分以外の人狼", Color.RED)
                bold(" ---", Color.GRAY)
                wolves.filterNot { it.player.uniqueId == wolf.player.uniqueId }.forEach {
                    bold(it.player.name, Color.GREEN)
                    appendln(":", Color.GRAY)
                    append("  >", Color.GREEN)
                    appendln(" ${it.propensity}")
                    appendln()
                }
            }
        }

        delay(5000)

        morning(true)
    }

    suspend fun CommandContext.morning(
        isFirstTime: Boolean = false,
    ) {
        SeihekiZinrou.step = SeihekiZinrou.Step.MORNING
        world!!.animateTime(plugin, 0)

        val deadPlayers = SeihekiZinrou.propensities.filter { it.killed }

        if (deadPlayers.isEmpty()) {
            server!!.playSound(
                Sound.sound(
                    org.bukkit.Sound.ENTITY_PLAYER_LEVELUP.key,
                    Sound.Source.MASTER,
                    1f,
                    1f
                )
            )

            title(
                "${SeihekiZinrou.day}日目の朝が来ました。".component(),
                "昨晩は誰も襲われませんでした。".component(),
                1, 3, 1
            )
            delay(5000)
        } else {
            server!!.playSound(
                Sound.sound(
                    org.bukkit.Sound.ENTITY_PLAYER_DEATH.key,
                    Sound.Source.MASTER,
                    1f,
                    1f
                )
            )

            plugin.runSync {
                deadPlayers.forEach {
                    it.player.gameMode = GameMode.SPECTATOR

                    it.player.title(
                        "昨晩、あなたは人狼に襲われました。".component(),
                        "あなたの性癖は参加者全員に公表されます。".component(),
                        1, 3, 1
                    )
                }

                server!!.broadcast(text {
                    bold("--- ", Color.GRAY)
                    bold("襲われた村人とその性癖", Color.RED)
                    bold(" ---", Color.GRAY)
                    deadPlayers.forEach {
                        bold(it.player.name, Color.GREEN)
                        appendln(":", Color.GRAY)
                        append("  >", Color.GREEN)
                        appendln(" ${it.propensity}")
                        appendln()
                    }
                })

                deadPlayers.forEach {
                    it.player.title(
                        "${SeihekiZinrou.day}日目の朝が来ました".component(),
                        "昨晩${deadPlayers}人の村人が襲われました".component(),
                        1, 5, 1
                    )
                }

                SeihekiZinrou.propensities.filter { it.killed }.forEach {
                    it.killed = false
                }
            }
            delay(7000)
        }

        if (isFirstTime) {
            val werewolfNumber = plugin.config.getInt("werewolf_number")
            val book = item(Material.WRITTEN_BOOK) {
                meta {
                    this as BookMeta
                    title("人狼の性癖".component())
                    author("ゲームマスター".component())
                    page {
                        boldln("----------------", Color.GRAY)
                        appendln("人狼は${werewolfNumber}匹存在します。")
                        appendln("(ゲーム開始時の匹数)")
                        boldln("----------------", Color.GRAY)
                        appendln()
                        SeihekiZinrou.propensities.filter { it.werewolf }.forEach {
                            bold("・", Color.GRAY).append(it.propensity, Color.ORANGE).appendln()
                        }
                    }
                }
            }

            server!!.playSound(
                Sound.sound(
                    org.bukkit.Sound.ENTITY_ITEM_PICKUP.key,
                    Sound.Source.MASTER,
                    1f,
                    1f
                )
            )

            SeihekiZinrou.propensities.forEach {
                it.player.inventory.addItem(book)
            }

            title(
                "人狼の性癖が公表されました。".component(),
                "公表された性癖を元に、処刑対象を話し合ってください。".component(),
                1,
                6,
                1
            )
            delay(7000)
        } else {
            title(
                "もうすぐ昼になります。".component(),
                "殺害された村人や、公表された性癖を元に、処刑対象を話し合ってください。".component(),
                1,
                6,
                1
            )
            delay(7000)
        }

        dayTime()
    }

    private fun CommandContext.dayTime() {
        SeihekiZinrou.step = SeihekiZinrou.Step.DAY
        world!!.animateTime(plugin, 4000)
        timer.cancel()
        timer = Timer()
        plugin.reloadConfig()
        count = plugin.config.getInt("time_day")

        val selector = item(Material.CLOCK) {
            enchant(Enchantment.LUCK)
            flag(ItemFlag.HIDE_ENCHANTS)
            displayName("右クリックして処刑者を選択")
        }

        timer.scheduleAtFixedRate(1000, 1000) {
            count--
            if (count <= 0) {
                SeihekiZinrou.propensities.forEach {
                    it.player.inventory.remove(selector)
                }
                selector.unRegister()
                scope.launch { punishment() }
                cancel()
                return@scheduleAtFixedRate
            }

            if (count == 30) {
                title("残り30秒".component(), "処刑者を選択するアイテムが与えられました。".component(), 1, 3, 1)

                val menu = BasicMenu.createInstance {
                    SeihekiZinrou.propensities.forEach { propensity ->
                        runBlocking {
                            item(HeadUtil.getHead(server!!, propensity.player.name) ?: dev.kotx.flylib.utils.item(Material.PLAYER_HEAD) {
                                type(Menu.Type.LARGE_CHEST)
                                displayName(propensity.player.name)
                                meta {
                                    this as SkullMeta
                                    owningPlayer = propensity.player
                                }
                            }) { event ->
                                SeihekiZinrou.propensities.forEach { it.votes.removeIf { it.uniqueId == event.whoClicked.uniqueId } }
                                propensity.votes.add(event.whoClicked as Player)
                                event.whoClicked.send {
                                    bold(propensity.player.name, Color.GREEN)
                                    append("を処刑者として選択しました。")
                                }
                                close(event.whoClicked as Player)
                            }
                        }
                    }
                }

                server!!.onlinePlayers.forEach {
                    selector.onClick(it) { event ->
                        menu.display(event.player)
                        false
                    }

                    server!!.playSound(
                        Sound.sound(
                            org.bukkit.Sound.ENTITY_ITEM_PICKUP.key,
                            Sound.Source.MASTER,
                            1f,
                            1f
                        )
                    )

                    it.inventory.addItem(selector)
                }
            }

            if (count == 15) {
                world!!.animateTime(plugin, 12800, 200)
            }

            SeihekiZinrou.propensities.forEach {
                it.player.sendActionBar(text {
                    append("あなたは")
                    if (it.werewolf)
                        bold("人狼", Color.RED).append("です。").append("人狼であるとバレないよう立ち回り、誰を処刑するか話し合ってください。")
                    else
                        bold("村人", Color.GREEN).append("です。").append("性癖を元に人狼を推測し、なるべく早く処刑してください。")

                    when {
                        count in 10..30 -> append(" || ").append("残り${count}秒", Color.ORANGE)
                        count < 10 -> append(" || ").append("残り${count}秒", Color.RED)
                        else -> append(" || ").append("残り${count}秒", Color.GREEN)
                    }
                })
            }
        }
    }

    private suspend fun CommandContext.punishment() {
        SeihekiZinrou.step = SeihekiZinrou.Step.SUNSET
        val target = SeihekiZinrou.propensities.maxByOrNull { it.votes.size }!!
        plugin.runSync {
            target.player.gameMode = GameMode.SPECTATOR
            target.dead = true
        }

        target.player.title(
            "あなたは処刑されました。".component(),
            "ゲームが終了するまではチャットは出来ません。".component(),
            1,
            5,
            1
        )

        SeihekiZinrou.propensities.filter { !it.dead }.forEach {
            it.player.title(
                "${target.player.name}が処刑されました。".component(),
                "誰が誰に投票したかはチャット欄で確認できます。".component(),
                1,
                5,
                1
            )

            it.player.send {
                append("-----------", Color.GRAY).bold("投票結果", Color.GREEN).appendln("-----------", Color.GRAY)
                SeihekiZinrou.propensities.forEach {
                    bold(it.player.name, Color.GREEN)
                    appendln(":", Color.GRAY)

                    it.votes.forEach {
                        append("  > ").appendln(it.name, Color.GREEN)
                    }
                    appendln()
                }
            }
        }

        SeihekiZinrou.propensities.forEach {
            it.votes.clear()
        }

        delay(7000)

        nightTime()
    }

    private suspend fun CommandContext.nightTime() {
        SeihekiZinrou.step = SeihekiZinrou.Step.NIGHT
        world!!.animateTime(plugin, 14000)

        plugin.reloadConfig()
        val nightTime = plugin.config.getInt("time_night")

        SeihekiZinrou.propensities.forEach {
            plugin.runSync {
                it.player.gameMode = GameMode.SPECTATOR
                it.player.addPotionEffects(
                    listOf(
                        PotionEffect(
                            PotionEffectType.INVISIBILITY,
                            nightTime * 20,
                            1,
                            false,
                            false,
                            false
                        ),
                        PotionEffect(
                            PotionEffectType.BLINDNESS,
                            nightTime * 20,
                            2,
                            false,
                            false,
                            false
                        )
                    )
                )
            }

            if (it.werewolf) {
                nightMenu = BasicMenu.createInstance {
                    title("誰を殺害するかを決めてください。")
                    type(Menu.Type.LARGE_CHEST)
                    SeihekiZinrou.propensities
                        .filterNot { it.werewolf }
                        .filterNot { it.dead }
                        .forEach { propensity ->
                            runBlocking {
                                item(HeadUtil.getHead(server!!, propensity.player.name) ?: dev.kotx.flylib.utils.item(Material.PLAYER_HEAD) {
                                    type(Menu.Type.LARGE_CHEST)
                                    displayName(propensity.player.name)
                                    meta {
                                        this as SkullMeta
                                        owningPlayer = propensity.player
                                    }
                                }) { event ->
                                    onClickTarget(server!!, propensity, event)
                                }
                            }
                        }
                }

                plugin.runSync { SeihekiZinrou.propensities.filter { it.werewolf }.forEach { nightMenu?.display(it.player) } }
            } else {
                title("夜が来ました。".component(), "人狼の行動が終わるまで暫くお待ちください。".component(), 1, 5, 1)
            }
        }

        delay(nightTime.toLong() * 1000)

        val targets = SeihekiZinrou.propensities.filter { it.votes.isNotEmpty() }
        targets.forEach {
            it.killed = true
            it.dead = true
        }

        morning()
    }

    private fun BasicMenu.onClickTarget(server: Server, propensity: Propensity, event: InventoryClickEvent) {
        propensity.votes.remove(event.whoClicked)
        propensity.votes.add(event.whoClicked as Player)

        event.whoClicked.send {
            bold(propensity.player.name, Color.GREEN)
            append("を殺害対象として選択しました。")
        }

        update {
            title("誰を殺害するかを決めてください。")
            type(Menu.Type.LARGE_CHEST)
            SeihekiZinrou.propensities
                .filterNot { it.werewolf }
                .filterNot { it.dead }
                .filter { it.votes.isEmpty() }
                .forEach { propensity ->
                    runBlocking {
                        item(HeadUtil.getHead(server, propensity.player.name) ?: dev.kotx.flylib.utils.item(Material.PLAYER_HEAD) {
                            type(Menu.Type.LARGE_CHEST)
                            displayName(propensity.player.name)
                            meta {
                                this as SkullMeta
                                owningPlayer = propensity.player
                            }
                        }) {
                            onClickTarget(server, propensity, event)
                        }
                    }
                }
        }

        close(event.whoClicked as Player)
    }
}