#!/usr/bin/env sh

#
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWNNNNNNWWWNNWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWNNNNNNNNWWNNNNWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNWWWWWWNNNNWWWWWWWWWNNWWNWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNWWNWNNNNWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWNWWWWNNWWWWWNNWWWWNNNNNNNNNNNNNNNNNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNWNNWNNWNNNNNNNXXXKKK00000000000KKXXXXNNNWWWWWWWWWWWWWNXKK0OOkkkkkO0KXNNNWNWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWNNNNNNWNNXK0kxddolccc:;;,;;;;;,;;;;;:clodxO0KKKKKXXNNNXKOkxdlcc::;;,,;:cloxO0XNNWWWNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNKOxoc::::cccccccccccllllccllllllllooddxxxxxxxxkkxxxdoddoooooooolcc:;,,;:cldk0XNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXko;,,;:cllllllllooooooooooooooooodddoooooodooooodoooooooooooodoooddddooolllc:::cldOKXNNNNWNNNNNWWNNNNNWNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWNNXx:'';cclllllcllooollooooolllllloollllllllllllloollloooooooooollooooooooooooddooolc;,,;coxOKNNNWNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNWWNX0o;';ccllccllllllccllllollloollllooollllooooollllolooloooooooooolooooooooooooooodddollc:;,,,:lxOKXNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNX0kxol::cccclccccllllllllllloooooooollllllllooooooooooooollooolloooooollloollooooooooooooloolllc::;;:ldk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNN0d:;;cllcccllllllccllllllollooooooooooolooollooloollllllloooooolloolllooooloooolooooooolllllooloooooolccccloxkOOO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWXk;'';:cclccclllllllllllooooloolloooloooooooooooooooolllllooooooooolloooolloooooooloooooooooollloooooooooooooooolccloxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNWWNWXx,.,clcclcccllllllllooolloollloolloooooooolooooooooolllllloooolooooloooooollloooloolllooooloolloooooooooodooooddoollllclxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWNNNO;.,:ccclllccllllooooooollooooloolloooooooloooooooooooollllloooooolloooooolooooooooollllloolloooooooooooooooooooooooooollcclx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNKl'':llllllollollllloolooooooooooooooooooooooooooooloolloooooooooolloooooooooolooooooolllllloooolooooooollloloooooooooooooolccclkXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNNNNWNO:';cloooloolooooolooooollllloooloooooooooooooloooollollooooooooooooolloooooooolooooollllloolooooooooololloooollooooooooodooooc::lkKNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNWNNWNXx,':loooooooooooooooooooooollooooooooooooddoooooooooooollooooooolooodooooollooolooooolllloollloooooloolooloooollllllooooooooooooc::lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNWWNNNNWNNNNKl',clooooooooooloooloooooooooooooooooooooooooooooooooooooooooodoooooooooooooolloooooolllllllloolooolooooooooloooolloooooooooooooolc::oOXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNN0c.,clooooooloooolooooooloooooooooloooooooooodolooooooooooooolooooooooooooooooolloooooollllloolllooolloolloooooooooloollllllloooooool:;:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNXKKK0KKXNNNWNNO;.;loooooooooooooolooolooooooodoooooooodddooodoodooooooloooooooooooooooooooooooooooolooooloolllloollolllllolloooooollolllooooooooooool:;ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNNNNNNNXKOxoc:;::clldkKXXKd,.;looooooooolllllooooooooooddddddddodddddooodddddddoooooooooooooooooooolooooooooooooooooooooollllllollooooooolloollloooloollllllooooolc;:o0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNNX0xo:;,,,;:::c::::coxkko,.;loooooloooollooooooooooooooddddddoodddddoodddddddddddddddddoooooooooooooooooooooooooooooooolllllllllllolooolooollooollllllllllloooollc:;ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNN0xc;',;::ccclllllllllllodl,.,coooooooooooooooooooodoooodoooddodddddddodddddddddodddddoooooddddooooolooooooooooooolooooollllllllllllloolllooollollllllllolllllloooool:;:dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0o;',;:clllllllllllllllllllc,.'coooooooooooooooooodddddooooooodddddddddddddddooddddddddooooododddodoooooolooooooooooooolllooollllollloooolloolloolllllllollllolooloooolc;;o0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNXx:,;:cllllllllooollolllllllol:'.,loddooooooooooooooolcc::;;;;;::clooodddddddddddddddddddoooooooodddddddddoooooooooooloooooollllloolloollollloolloooolllllolllooollllooolll;,:kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNKxlcclllllollllllllloooloooooool:'';loooddoooooolc:;,'''''',,,,,,,,;;:clodddddddddddddooodddooooooooooodddddddoooooooolloooooooloooooooollloooooollooollollllooollloolllloool:;;o0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNX0xolllllllllooollloooooloooooooooo:,;:lodddooool:'''',;:clloooooooolllcclloooodddddddddddddooooooolloooodddddddooooooodooooooollooolloooollooooollooollllollllloollllollloooool:;;lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXkooolllloooooooooooooooooooollooooollccloddoooolc,,;coodddoooooooooooooooolc::cloddoddooddddoodooooooooooooodddddddoooooooooooooooollloooooooooollloolollllllllloolllllllllllloolc;,:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXOocclolloooooooooolollllloooolloooooooooooddoooooolloddollcccccllloooooooooolc:;:coooooooddddooolooooooooodoooooddddddooooooooooooooolllooooolooloololloollloloolllooooollllllollllc;,:d0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKko:;cllllooooolloooooooollloolooloooodoooooodoooooooollc:::::cccllllooooooooooool:;;cooolooooooooooooooolloooddoooodoodoooloooooooooooloooloooooooooooooooollloolllooolollollllllloolc;,;o0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xl:;:looooooooolooooooooooooolllllooooooooddoooooooolc:::cllollooooooooooloooddooooc:;:llloooooooooooooooolloooddooooodddoooooooooooooolooolooooloolooooooooooloolllllolllllllllllloooll:;:okKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xl:;:loooooooooooooooooooooddoolloooooooooddddoooooc:;:clooooolloooooooooooooooooddool:,;clllloooooooooooollloooooodooooddoddooooooooooooooooooolloooooloooooooooolllllolloollllllllllllllccccoOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0dl:,;looooooooooolloooooooooooooooooooooooooooodool;;:cooooollllllllccccc::clloooooooooc;';cllllllooololllloolooolodddooooooddooooooooooooloooooooooooooooloooooloooollllllllllllllllooollolollclxKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxl;,;loodoooooooooooooolooolooooodoodolooooooooodo:,,:oddollllcc:;,,'''''',,;clooodoooodo:,,:llllllllloooollloollloooodooooooooooddoooooddooooooooooooooooollllooloolollllolooooollllollloooloolllld0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl;,;cooooollllool:;,,,,,,,;;:cclloodoooooooodoodo;',cooddolc;,''.',,;:cclllllloooooodddddo;';clollllllllloololllllooooodddoooolc:clooooodoooooooolooooooloooooooooollolloooolllllloloolllllllooooolcoOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0o,';loooolcccllooc:;;;;;;,,,''.'',;:cooodoooodool;',coddol:,''',:ccccc:;;;,,,,',;cooodddooo;',:lolllllllllollllllllloolloooooool:,'coooooooooooooooooooooooooooloooooooolloooolllllloollllllooooooollcoOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKo,';looooc:;:loooooooddoooooollc:;,'.',:loooooodl;';lddoc;,,;:cllc:,'''.'',;;:;;;:coooddddol:..:lollcllllloolllllllllll::loodddool;',:loooddoooooooooooooooooooooooooolooooolllllllllloolllooolllllloolco0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo'.;loodoc;;:loooddooddoooddddddddoll:;'.';codool:,:odoc;:coxxdoc,''',;:cclooddddddddooodddoo:'.;loll:;:llllooolllloollc:;clooodddol;',coooddooooodoooooooooooloooooollllooooloooooooolooooolllolllllooolco0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMM
# MMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,.;lloooc,,:oddddddddddddoooolccclllloolc,'';ldoc:lxkkdoxOKKXXKx::ldddoolccc::::::::::codddooc'.;clll:,;cllllooollllloll:;:clooodoolc;',:llooooooodooooooolooooooooooolloooooodoooooooooolllllllollllooolccdKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMM
# MMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.;loool:''coddddddoddool::;,,''''',,;:loddc,',ldxk0KXXXXNNNNNNNX0KXKxl;,,,,;,;::::;;,'',:loooc,.,clllc;,;clllloolllllolll:;:cloooooool:'';cooddddooooooooollllooooooooooooooooooooooooooooloolllllllooooolcckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMM
# MMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;';loool:'':oddodddool:;'''',;:ccccccccccldxxdlcoOKXNNNNNNNNNNNNNNNNNKkooxkO0KKKK0xolclloooooool;.,:llll:,';cllllooolllollll:;:cloooooooo:,',cododoooooooooooolllllcloooooooooooooooooooooooooolllllllolooooc:lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMM
# MMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNO:.;loool;'':oddoooolc;'',;:llodddddooddddxk0KXXX00XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOkkkO0KK0kddol;..;clool:,';cllllooollllloolc;;:looooooooc;'';cooooooooooooooolllc;:cloooooooddooooooooooooodoollloollllooolc:dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMM
# MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl',coool:'':odooooll:;::looododdddddooodk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxdo:'.;clolll:,';clloooooollllooll:;:clooooooooc,'';coooooooooooolloll:,,:lodooodoollooooooodooooooooolllllllodol;ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMM
# MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,':looo:'.;looooooolllooooooddoolccccldOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOkxdl,.,;collllc,'':cllooolllllllolc:;;:loooooddolc,'';clooooddddoooooll:,',:loooooolooooooodoooooodooooloollloddl;;dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMM
# MMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKc',coooc,.,cllooooodooooddoodol:;;;cldOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOxddc,,,:lllllll:'',:looooloolloollll:;;cloooddddooc,'',:looddddoodddoooc:,',:cloooooooooooooollooooooooooolloodl;'c0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMM
# MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk,':lodl;.'coolloooodoooooolc:;,;:ldx0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kddo:,',:lllllllc;'';cllloooolollooolc;,;clooddoooolc;''';clododdddooooool:,'';clooooloooooooooooooooooooooooodo:';kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMM
# MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd'':loo:..;looooooooooooooc,'':lodddkKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kxdo:;,,:lloollolc;'';cloooooollloooll:;,;coddddolcccc:;'',:clooodoooooooooc;'',:coooooooooooollooloooooooooloo:.,dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMM
# MMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo''cll:'.,coooooooooooooc;'':lodocclkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kkxol:'';cllllloolc,'',:looooollloooooc;'';loodddlc:clll:;'',;:coooooooddddol;,'':cloooooooooolloloooolloooloo:''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMM
# MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0l,:lol,.'coooloolcoooolc,.,coooc;;oOXNNNNNNNNNNNNNNNNNNNK0OOKXNXKOkO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kxxdoc,',:lllllllll:;''';cooolllllooool:,'':looddolc:cclllc;,'',;clooodddddool:;'',cllooloooooooooooooooloool:''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM
# MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXklcloo:..;loooolc:clool:'.;lool;,;dKNNNNNNNNNNNNNX0OO00KK0koccox0Odc;:okKNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0Okxxdl:'',:lllllloool:,'',:loooollooddol:,',:lodddoolc:cloooc:,,'',:cloddooooooc;'',:llllloooooooooddooooloo:.'cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
# MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKxllooc,.,coolol::cllol:'.;lool;':xKNNNNNNXK0O00K0xl:;;;:cldxxol:cdkOko:;lxKNNNNNNNNNNNNNNNNNNNNNNNNNNNKkdlllddl;'',,,,;clllccc:;'',;cooooooooooooc,',:loddddolcc:cldddlc:;,'',;:codoooool:,'';clllooooooooooooollol;.,lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
# MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOolooo;..;looll:;:lllol;',cooc,'cOXNNXXXXKkdc:;::::::loddoc:;:ldxoccok0Od:;lOXNNNNNNNNNWNNNNNNNNNNNNNKOdlccloxxl;,'...',;,,'',;clc:,'',:looooloooool:'.';lodddddolc:clddodolc:;,''',:loooool:,'';cllooooooloodoololc;.,lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
# MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkooddc,.,coollc;;cooolc,':ooc,'cOX0xocc:cccccloxxdoc:;;:lxOOkoccoxOkdodO0Oo;:dKNNNNNNNNNNNNNNNNNNNX0xlcoxxxdl:;:cc:,......,;:::::;,,,,,,,;cooooooooooc,'.',:loddddol:::lodddddool:;,'',;cllool:,.';clooooollodoooooc,.;d0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
# MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkoloo:'.;loooc;,:lool::cclc:,':kXXOdllooooolclldk0XXKOxoc:cd0XKOxxOXXKOO0KKx:;o0XNNNNNNNNNNNNNNNX0xlcoxdl:::cllc:;,;clc;'.''''''''''',;,'.';cloddooloolc:,..,;loddddoc:;:loddddoodool:,''',:lool;'.':looodooooooooo:'.:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
# MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxllol:.':llol:,,codo:;coo:'..,d00kddooddddxkkO000KXNNNNNX0OOKNNNNXNNNNNNXNNXkccxKNNNNNNNNNNNNNNKxooxOOo:cxk00x:;cdkKKOo;'',,'..',,'...',,,,,;ccllllooolccc:;'.';codoodoc:;:loddoooododolc;,',:lllc,.':loooooooooool;.,lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
# MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkoooc,.,loolc,,:odo:,:oo:'..'lkd:;;::ccc:::loxKNNNNNNNNNNNNNNNNNWNNNNNNNNNNNXKOKNNNNNNNNNNNNNNKxoxKXX0kOKNNNXK0KXNNNKxccdO0kl,'',''..',,,,,'''',,,;loooc:::::;,'',:odddooc;;;coddoodoodddolc;,;:loc;'';cooooooooooc,.;dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
# MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xdoc'.,loll;';looc,,col'...:kK0O0KKXXXXXKKKKXNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX00XNNNNNNNNNNNNNNNNNNNXXXNNNX0kOOOko:;;:ccccc::cccccllooolc:;,;::;'',codddolc;,;loddddooolloool:::lol:'.,coooooc:cl:''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
# MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkdo:'.;lol:''cool:,;lo;...'l0NNNNNNNNNNNNNNNNNNNNNXXKXXKXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0O00KKKkl;,,,,,,''',:clll:;,,;:;,,;:codddoc;,;codddoc,;coddolcclol:'.,looll;,;:,.:ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
# MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxo:'.;llc'.,lool;':ol,...'cdddddddxxdddddoollllllc:::::::::::::::::cllodkOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXNNNNNNNNNNNNNNNNNNNNNNNXXKXXKOkkxdolllc:;;::;:cc:;,,;;,,',;codddl:,';coddl;'':oddooooool;.';lllc;',;',xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
# MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0dc'.;ll;..:lool:,:o:'''..',;:::::::ccccccccccllooodxxxxxxxxdxxxxdooolc:;;cx0XNNNNNNNNNNNNNNNNNX0xollllcccccllooooloooooddxxxxxxkkOOOOO0KKXNNNXK0Okxdolc:;,,;;;;,,;cc:;,;coddol;'':lool;'':looooooooc,.,clc:'.,:cxXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl'.;lc'.,cloodl;;,'.','.,o0XXXXKKK000OOOOOOO00KXXXXXXXKKKKXXNNWWWWWWNXOo;,lONNNNNNNNNNNNNNNKkl;;:cclllllllllllllllcc:::;;,,,,;;;;,,,;;:cldk0KXXKOxddolllc:;''',;cooooc,,;loddoc,';codo:'';lddoooool,.':cc,.'cx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx;':l:..;llodoc,','.,;'.c0WWWKxl::;;;,,,,,,,,,;;:::::;;,,;;:cllokKNWWWWXx;,o0NNNNNNNNNNNNNKo,;d0XXXXXXXXXXKKKKKKK0000OOkkkkkkOOOOOkkxdol:;,;cd0KOxolc;;:ccc:,'.,:loddol:',:loddl;',:odoc,';loddoooc,.';c;..:OXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo:cl;.'clodl;';dxc',:,.cOWWNk;.................................':xKWWWWKo,:kXNNNNNNNNNNNXd,;xKKkoccccccc::;;;;;;;;;;;;;;;;;:ccloxk0KXNNX0ko;,cdl;,''......'''',;coooodoc,';coddl;'':oooc,.;lddool:..,::'.;kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxoc,.,codl,'cOX0l',lc,;dXWNk;...................................,o0NWWNk;;xXNNNNNNNNNNNOc,o0Oc'.................................',;cdOXWWXx:,;ldocccc:,....';clllc::lodl;''codol;'':odo:.':lool:'.'::,.;kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxc'.,ldl,'l0NNKx;,ldc':kNNk;....................................'l0WMW0ook0OxooooodxkOd;,dKk;......................................':kXWWXd,,d0Oxollll:;'.,:looo:,';lool;'':lool;.,looc,.,col:'.,::,.;kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl,.,ll;':ONNNNKd:;cc,'c0Nk;.....................................;kNWWNOo:;;;:ccccc:;;,',dKO:.......................................'l0WWKo',okxo:;,;ccc;'.,coddl:,.;lool:'';ldoc'.:ool;.':llc::c:,.,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkc',cc',dKNNNNNXOdll:,;xX0c.....................................;xNWNOl;cdOKKXXXXK0Od:,,oKKo'.......................................;xNNOc'';:;,'.....''..',cdddoc'.;lool:'':lol,.;ldo;.':oolclc,.,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0l,''':ONNNNNNKOxol:',oXXd,....................................:OWNk:;dKNNNNNNNNNNNXOc,lKXx;.......................................,dXXd,':l:;,,,,'..'',,',codddo:''coool;.,coc,.;loc,.,ldoolc,.,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo,.':OXNNX0dc,',:c;'c0N0l'..................................;xXWXd,;xXNNNNNNNNNNNN0l,l0NO:.......................................,xXOc':kx:'.............'',;col,';oddo:'':l;.':l:'..,ldool;.,xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:.':dxdc,',cdOK0l';xNNk;.................................;xXWWKl':kXNNNNNNNNNNNNKo,cONXd,.....................................'cO0o';dKOl:;;;;,'':oddddl:;,'','.,lxdo:',c:,;c:,'...;lool;':kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,';:,.':oOXNNNXk;,oKWXd;...............................:kNWWXx;,oKNNNNNNNNNNNNNXx;:kNNO:.....................................;xKd,,oKNKOxl;,:lox0XNNNNNX0Odc,..':odoc:loooool:,..':clooldKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0l,''';d0NNNNNNNO:.:ONWXx:'...........................,l0NWWXx;,lOXNNNNNNNNNNNNNNO:,oKWXd,...................................,d0k;'c0NNKOdc,.'ckXNNNNNNNNNNNXOo:'.':ldxddxdol;'...,;;:d0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,.'lOXNNNNNNNNKd;,l0NWNOl,........................,lONWWN0o,,l0XNNNNNNNNNNNNNNNKo,:ONW0l'.................................,oOx;'cOXNNX0x:',:x0NNNNNNNNNNNNNNX0d;..;odlc:;,'',;,',:;;lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo,.;xKNNNNNNNNNNNXx:,cxKNNKxc,'...................,lONWWWXx;':xKNNNNNNNNNNNNNNNNNXk:,l0WN0o,..............................,lkOo,,l0NNNNNXKOookXNNNNNNNNNNNNNNNNNXkc'.',,'.',cll:'':l;,cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo,.:kXNNNNNNNNNNNNNXOo:;cd0XNX0xl;,''.........',:ld0NWWWWKo,,lOXNNNNNNNNNNNNNNNNNNNXx;,oKNWXOl:;'.......................';oOXOc';dKNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNOl,.',,';ldo:'';c:,,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.;xXNNNNNNNNNNNNNNNNXOo:,;lx0KXXK0OkxdoooooxkOKXNWWWWX0d:,;o0NNNNNNNNNNNNNNNNNNNNNNKx:;lONWWNXKkoc;''................;okKX0d;':kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0l'..'':oo:'.,::''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0c.'oKNNNNNNNNNNNNNNNNNNNXKxl;,,;cldxkO00KK0KKKKKKKK0Oxo:;,:d0XNNNNNNNNNNNNNNNNNNNNNNNNXOdoloxKXNNWNXKOkdoc::;;;,,,,;:ld0XKko;,:d0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk:...':l:'.';;''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.:kNNNNNNNNNNNNNNNNNNNNNNNX0kxol:;;;,;;;;,;;;;;;;;,,,:cdOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0xc;;cloxkO0KKKK0OOOOkkxxxxxxxoc;,;cx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXd,..,::'.';,.,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo''lKNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0Okxdddddddddddxxk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkdllc:;;;:::::::;;::::;;;;;clox0XNNWNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNN0c..,;'..''';xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo''oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0OOkkkkkkkkkkkkkkO00KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0l'.','...,lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd,'cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO:.':c,',lkXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
# MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0c',o0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXd,.;odox0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
# MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0c',lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNX0Okkkxdl:;,'',,:ldxOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXx;.,dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
# MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKo,'ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk:,,'''',:coxxdl:,'',;coxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk;.'oKNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
# MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd,.:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0kxxxxxO0KXNNNNXKOxdl:,'':kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKd;.,oKNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
# MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:',:ok0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kxx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNKxc'.:xXNWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
# MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxl;'';cdk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOo:'';o0NWWWNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
# MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWNKkoc,',;coxk0KXNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNXKOkdl:'.,cxKNNNNWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
# MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWNX0xoc;''',:coxO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kxxdooolllooooddxxxkkkkxxxddoooollc;''',:ldOXNWWWNWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
# MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNWWNWNNXKOxoc;,''',:codxk00KXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kdl:;,',;;:::;;;,,,''''''''''''''''',,,;:cldk0XNNWNWWWNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
# MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNX0Oxoc:;,''',;:::ccllooddxxxxxxxxxxkO00KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKko:,'',:odkOKKXXXXKKK0OkkkOOkkkkkkkkkOO000KKXNNNWWWWWWWNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM
# MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXKOkxdolc::;;;,,''''''''''''''',;;;codkO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0dc;,;cdk0XNNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM
# MMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWNNWWWWNNXXXXKK000Okkkkkxxxxxxxxddlc::;;;;:ldkOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNKxc;cx0XNNWWNNWWNWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMM
# MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNWWWWNWWWNWWWWWWWNNNWWNWWWNWWWWNWNNXXK0kxdoc:;:lkKXNNNNNNNNNNNNNNNNNNNNNNNXOl,,l0NWWNWWWWNNWWWWWWWWWWWWWWNWWWWWWWNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMM
# MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWNWWNWWWWWWWWWWWWWWWWWWNNKkl,,cxKNNNNNNNNNNNNNNNNNNNNNXx;',dKNWWNWWWWWWWNWWWWWWWWWNWWWWWWWWWWNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMM
# MMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:';dKNNNNNNNNNNNNNNNNNNNXx;.;xXWWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMM
# MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx,.:kXNNNNNNNNNNNNNNNNNNOc.':oxOXWWNWWWWWWWWWNNNNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMM
# MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0Oxo:'.,dXNNNNNNNNNNNNNNNNNNOc'':c:cd0XNWWWWWWWWNNNNNNWWWWWWWWWWWWNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMM
# MMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNWNWWWWWWWWNNNXKKKKK00ko:''',;'.,oKNNNNNNNNNNNNNNNNNN0l':kKkc:codxOKXNNNWWWNNNNNNNNWWWWWWWWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMM
# MMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNNNWNNNNKOkdolc:;,,,,,''''..:kk:.,dKNNNNNNNNNNNNNNNNNNO:'cOOc,ckOo;,;:cldxOKXNNNWWNNWWWWWWNNNNNNNNNNNNNNNNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMM
# MMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNWWNKkoc;,;:clllc:,..;oxkx:,o0x,.;xXNNNNNNNNNNNNNNNNN0c,:xx:,cONWXOl'..,;;;:lxKNNNNNWWWWWWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMM
# MMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOo;,;ldOKXNWWWNOc.'oXWNO:,okl'.:OXNNNNNNNNNNNNNNNXk:':xx:,c0NWWNk:.'ckKKOd:;cxKNNNNNWWWNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOo:',cxKWWMMMMMMWWKl''lKWWO:'::'.'cOXNNNNNNNNNNNX0kdl,'cxo;,l0WWWKd;.'l0WWWWN0d:;:dOKNNNNWWNNWNWWNNWWNNWWWWNNWWWWWWWWWWWWWWNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXko;,;cx0NWWMMMMMMMMMWXd'.:OWW0l,,cl:,,:coxxkkkkkkxoc;'.';dxl,;dKWWXkc'.;xKWWMWWMWNKxl;;:d0XNNWWNWNNNWNWWNNNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKkl;,,lkKNWMMMMMMMMMMMMMWNx;.;kNWNk:,o0KOdl:;;;,,,,,,,;::,'':c;,cONWW0l,.,l0NWWWMMWMMMWWN0dc;;lx0XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNX0kl,';lx0NWMWMMMMMMMMMMMMMMMWOc.'oKWWXx;,ckKXNXXK00OOOO000Od,...':xKWWXkc'.:kXWMMMMMMMMMMMWWWNXOo:;;lx00KXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0kxdlc;,';lkKNWMMMMMMMMMMMMMMMMMMMMWXx;.,oKWWXd,.,;codxkkkkkkxdoc:,'',cxKWWXkl,.,l0WWMMMMMMMMMMMMMMMMWWNKOo:,,;;:ccllodxkKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOd:,,,;:coxOKNWMWMMMMMMMMMMMMMMMMMMMMMMWXx;''ckXN0xdxdlc;;,,,,,,;;:lodkO0NWN0d:'.,ckXWMWWMMMMMMMMMMMMMMMMMMWWNKOkxdoollcc:;;:d0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0d:,,:dOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOo,',:oxkOXNNXK00OOO00KXXKkxk00kdc,.';oOXWMMWMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNXKkl;;cxKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd;':dOXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOo:,'.',:loddddddddodoo:''''''.',cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0d:,:xXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:':xXWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXOo;'','''''''''''''''',:ccoxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWKd;,ckXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo,,o0WWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWN0kO00OOOOOOOOOOOkkOOKNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWWN0o;,l0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,,oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMNOdkXWWWMMMMMMMWKxd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOc,:xXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;'lKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,lKWWMMMMMMMW0l;lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0o;,lOXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl':ONWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxlxXWWMMMMMMWNOdxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXOl;;o0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;'dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKk0NWWMWWWWXkokXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXx:,l0NWNWWWWWNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx:l0WWWWWNOc,:xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWNk;,oXWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWN0:'lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx;:kNWWN0o:lxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWKl'c0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNWWWWWNNNWWWWWWWWWWWWWWWWNNNk;,dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKolkXWN0c,oKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXx;,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNWNNNWNNWWWWWWWWWWWWWWWWNNWNO:'oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxcccll:,;xNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOl,,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNWNNNNNNNNNNNNNNNNNNNNNNNN0c'c0WWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0d:',:cclkNWWMMMMMMMMMMMMMMMMMMMWWNWMMMMMMMMMMMWNXNWMMMMMMMMMMMMMMWNNWWMMMMMMMMMWWXOl,,ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNXd;;xKNWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc,';ldkKNWWWMMMMMMMMMMMMMMWMWN0dco0NWWMMMMMWN0dc:dKWWMMMMMMMMWWN0dccxXWMMMMMMMWNkc,;lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNXkc:cdOXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,':l:;dXWWWMMMMMMMMMMMMMWWNOc'..:kNWMMMWNX0d;..,oKNWWWWWWWWNKkl,.,lONWMMMWWWXkl,,o0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNWNNWNNXkl;;lx0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWN0d:'':c,':ox0NWMMMMMMMMMMMWNKx;..'oKNWWNKOdc;'..'',:xXWNX0kdol:;'..:kNWWWWNXKko:,;oONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNWWNNNNNNNNNNNNNNNNNNNX0xc;;cldkKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOdolcc::::clkXWMMMMMMWWWWKxc,....,o0KOoc,..';coxl,.'cdoc;'..',;;,..cOXKOxoc:;,;lxKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNX0xoc;,;cd0NWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNWWMMMMMMWNX0o,..,:;...;:,...;cdOXNNKl'.....':ldxO0KOc..,::;,,;cox0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkd:,;oOXNWWMMMMMMMMMMMMMMMMMMMMMWWMMMWWWWWWWWWWWWWWWWMMWWMWWMMMMWNOl;'..:xK0l'.....;oOKNWMMWXd,..';coxkOOxdlc;'.',:ldk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkl;;:lxO0K0OxdddddddddxxxxxxkkkkxdoolcccccloooooddxkOO0KXXNXX0o,...:d0XX0l'.',cxOKKKKKKKK0d:,,clc;,'',,;:loodkKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xoc;;;;,',;;;;;;;;;;;;;;;;;;;;;:ccllllcccccc::;;;,,,;;:::;,....';;:::;'..',;;;;,,,,,;;;,,',,,,;;:oO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxxk0KKKKKKKKKKKKKKKKKKKKKXNNNNNNNNNNNXXXKK00OkxxxxxxddddooooooooooodddxxddxxdddxxxxkO000KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#
#

##############################################################################
##
##  Gradle start up script for UN*X
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`

    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$SEP$dir"
        SEP="|"
    done
    OURCYGPATTERN="(^($ROOTDIRS))"
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGPATTERN" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
        CHECK2=`echo "$arg"|egrep -c "^-"`                                 ### Determine if an option

        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                    ### Added a condition
            eval `echo args$i`=`cygpath --path --ignore --mixed "$arg"`
        else
            eval `echo args$i`="\"$arg\""
        fi
        i=`expr $i + 1`
    done
    case $i in
        0) set -- ;;
        1) set -- "$args0" ;;
        2) set -- "$args0" "$args1" ;;
        3) set -- "$args0" "$args1" "$args2" ;;
        4) set -- "$args0" "$args1" "$args2" "$args3" ;;
        5) set -- "$args0" "$args1" "$args2" "$args3" "$args4" ;;
        6) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" ;;
        7) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" ;;
        8) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" ;;
        9) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" "$args8" ;;
    esac
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=`save "$@"`

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

exec "$JAVACMD" "$@"
