/*
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWNNNNNNWWWNNWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWNNNNNNNNWWNNNNWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNWWWWWWNNNNWWWWWWWWWNNWWNWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNWWNWNNNNWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWNWWWWNNWWWWWNNWWWWNNNNNNNNNNNNNNNNNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNWNNWNNWNNNNNNNXXXKKK00000000000KKXXXXNNNWWWWWWWWWWWWWNXKK0OOkkkkkO0KXNNNWNWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWNNNNNNWNNXK0kxddolccc:;;,;;;;;,;;;;;:clodxO0KKKKKXXNNNXKOkxdlcc::;;,,;:cloxO0XNNWWWNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNKOxoc::::cccccccccccllllccllllllllooddxxxxxxxxkkxxxdoddoooooooolcc:;,,;:cldk0XNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXko;,,;:cllllllllooooooooooooooooodddoooooodooooodoooooooooooodoooddddooolllc:::cldOKXNNNNWNNNNNWWNNNNNWNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWNNXx:'';cclllllcllooollooooolllllloollllllllllllloollloooooooooollooooooooooooddooolc;,,;coxOKNNNWNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNWWNX0o;';ccllccllllllccllllollloollllooollllooooollllolooloooooooooolooooooooooooooodddollc:;,,,:lxOKXNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNX0kxol::cccclccccllllllllllloooooooollllllllooooooooooooollooolloooooollloollooooooooooooloolllc::;;:ldk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNN0d:;;cllcccllllllccllllllollooooooooooolooollooloollllllloooooolloolllooooloooolooooooolllllooloooooolccccloxkOOO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWXk;'';:cclccclllllllllllooooloolloooloooooooooooooooolllllooooooooolloooolloooooooloooooooooollloooooooooooooooolccloxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNWWNWXx,.,clcclcccllllllllooolloollloolloooooooolooooooooolllllloooolooooloooooollloooloolllooooloolloooooooooodooooddoollllclxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWNNNO;.,:ccclllccllllooooooollooooloolloooooooloooooooooooollllloooooolloooooolooooooooollllloolloooooooooooooooooooooooooollcclx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNKl'':llllllollollllloolooooooooooooooooooooooooooooloolloooooooooolloooooooooolooooooolllllloooolooooooollloloooooooooooooolccclkXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNNNNWNO:';cloooloolooooolooooollllloooloooooooooooooloooollollooooooooooooolloooooooolooooollllloolooooooooololloooollooooooooodooooc::lkKNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNWNNWNXx,':loooooooooooooooooooooollooooooooooooddoooooooooooollooooooolooodooooollooolooooolllloollloooooloolooloooollllllooooooooooooc::lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNWWNNNNWNNNNKl',clooooooooooloooloooooooooooooooooooooooooooooooooooooooooodoooooooooooooolloooooolllllllloolooolooooooooloooolloooooooooooooolc::oOXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNN0c.,clooooooloooolooooooloooooooooloooooooooodolooooooooooooolooooooooooooooooolloooooollllloolllooolloolloooooooooloollllllloooooool:;:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNXKKK0KKXNNNWNNO;.;loooooooooooooolooolooooooodoooooooodddooodoodooooooloooooooooooooooooooooooooooolooooloolllloollolllllolloooooollolllooooooooooool:;ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNNNNNNNXKOxoc:;::clldkKXXKd,.;looooooooolllllooooooooooddddddddodddddooodddddddoooooooooooooooooooolooooooooooooooooooooollllllollooooooolloollloooloollllllooooolc;:o0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNNX0xo:;,,,;:::c::::coxkko,.;loooooloooollooooooooooooooddddddoodddddoodddddddddddddddddoooooooooooooooooooooooooooooooolllllllllllolooolooollooollllllllllloooollc:;ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNN0xc;',;::ccclllllllllllodl,.,coooooooooooooooooooodoooodoooddodddddddodddddddddodddddoooooddddooooolooooooooooooolooooollllllllllllloolllooollollllllllolllllloooool:;:dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0o;',;:clllllllllllllllllllc,.'coooooooooooooooooodddddooooooodddddddddddddddooddddddddooooododddodoooooolooooooooooooolllooollllollloooolloolloolllllllollllolooloooolc;;o0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNXx:,;:cllllllllooollolllllllol:'.,loddooooooooooooooolcc::;;;;;::clooodddddddddddddddddddoooooooodddddddddoooooooooooloooooollllloolloollollloolloooolllllolllooollllooolll;,:kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNKxlcclllllollllllllloooloooooool:'';loooddoooooolc:;,'''''',,,,,,,,;;:clodddddddddddddooodddooooooooooodddddddoooooooolloooooooloooooooollloooooollooollollllooollloolllloool:;;o0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNX0xolllllllllooollloooooloooooooooo:,;:lodddooool:'''',;:clloooooooolllcclloooodddddddddddddooooooolloooodddddddooooooodooooooollooolloooollooooollooollllollllloollllollloooool:;;lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXkooolllloooooooooooooooooooollooooollccloddoooolc,,;coodddoooooooooooooooolc::cloddoddooddddoodooooooooooooodddddddoooooooooooooooollloooooooooollloolollllllllloolllllllllllloolc;,:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXOocclolloooooooooolollllloooolloooooooooooddoooooolloddollcccccllloooooooooolc:;:coooooooddddooolooooooooodoooooddddddooooooooooooooolllooooolooloololloollloloolllooooollllllollllc;,:d0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKko:;cllllooooolloooooooollloolooloooodoooooodoooooooollc:::::cccllllooooooooooool:;;cooolooooooooooooooolloooddoooodoodoooloooooooooooloooloooooooooooooooollloolllooolollollllllloolc;,;o0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xl:;:looooooooolooooooooooooolllllooooooooddoooooooolc:::cllollooooooooooloooddooooc:;:llloooooooooooooooolloooddooooodddoooooooooooooolooolooooloolooooooooooloolllllolllllllllllloooll:;:okKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xl:;:loooooooooooooooooooooddoolloooooooooddddoooooc:;:clooooolloooooooooooooooooddool:,;clllloooooooooooollloooooodooooddoddooooooooooooooooooolloooooloooooooooolllllolloollllllllllllllccccoOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0dl:,;looooooooooolloooooooooooooooooooooooooooodool;;:cooooollllllllccccc::clloooooooooc;';cllllllooololllloolooolodddooooooddooooooooooooloooooooooooooooloooooloooollllllllllllllllooollolollclxKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxl;,;loodoooooooooooooolooolooooodoodolooooooooodo:,,:oddollllcc:;,,'''''',,;clooodoooodo:,,:llllllllloooollloollloooodooooooooooddoooooddooooooooooooooooollllooloolollllolooooollllollloooloolllld0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl;,;cooooollllool:;,,,,,,,;;:cclloodoooooooodoodo;',cooddolc;,''.',,;:cclllllloooooodddddo;';clollllllllloololllllooooodddoooolc:clooooodoooooooolooooooloooooooooollolloooolllllloloolllllllooooolcoOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0o,';loooolcccllooc:;;;;;;,,,''.'',;:cooodoooodool;',coddol:,''',:ccccc:;;;,,,,',;cooodddooo;',:lolllllllllollllllllloolloooooool:,'coooooooooooooooooooooooooooloooooooolloooolllllloollllllooooooollcoOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKo,';looooc:;:loooooooddoooooollc:;,'.',:loooooodl;';lddoc;,,;:cllc:,'''.'',;;:;;;:coooddddol:..:lollcllllloolllllllllll::loodddool;',:loooddoooooooooooooooooooooooooolooooolllllllllloolllooolllllloolco0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo'.;loodoc;;:loooddooddoooddddddddoll:;'.';codool:,:odoc;:coxxdoc,''',;:cclooddddddddooodddoo:'.;loll:;:llllooolllloollc:;clooodddol;',coooddooooodoooooooooooloooooollllooooloooooooolooooolllolllllooolco0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,.;lloooc,,:oddddddddddddoooolccclllloolc,'';ldoc:lxkkdoxOKKXXKx::ldddoolccc::::::::::codddooc'.;clll:,;cllllooollllloll:;:clooodoolc;',:llooooooodooooooolooooooooooolloooooodoooooooooolllllllollllooolccdKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMM
 * MMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.;loool:''coddddddoddool::;,,''''',,;:loddc,',ldxk0KXXXXNNNNNNNX0KXKxl;,,,,;,;::::;;,'',:loooc,.,clllc;,;clllloolllllolll:;:cloooooool:'';cooddddooooooooollllooooooooooooooooooooooooooooloolllllllooooolcckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMM
 * MMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;';loool:'':oddodddool:;'''',;:ccccccccccldxxdlcoOKXNNNNNNNNNNNNNNNNNKkooxkO0KKKK0xolclloooooool;.,:llll:,';cllllooolllollll:;:cloooooooo:,',cododoooooooooooolllllcloooooooooooooooooooooooooolllllllolooooc:lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMM
 * MMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNO:.;loool;'':oddoooolc;'',;:llodddddooddddxk0KXXX00XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOkkkO0KK0kddol;..;clool:,';cllllooollllloolc;;:looooooooc;'';cooooooooooooooolllc;:cloooooooddooooooooooooodoollloollllooolc:dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMM
 * MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl',coool:'':odooooll:;::looododdddddooodk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxdo:'.;clolll:,';clloooooollllooll:;:clooooooooc,'';coooooooooooolloll:,,:lodooodoollooooooodooooooooolllllllodol;ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMM
 * MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,':looo:'.;looooooolllooooooddoolccccldOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOkxdl,.,;collllc,'':cllooolllllllolc:;;:loooooddolc,'';clooooddddoooooll:,',:loooooolooooooodoooooodooooloollloddl;;dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMM
 * MMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKc',coooc,.,cllooooodooooddoodol:;;;cldOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOxddc,,,:lllllll:'',:looooloolloollll:;;cloooddddooc,'',:looddddoodddoooc:,',:cloooooooooooooollooooooooooolloodl;'c0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMM
 * MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk,':lodl;.'coolloooodoooooolc:;,;:ldx0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kddo:,',:lllllllc;'';cllloooolollooolc;,;clooddoooolc;''';clododdddooooool:,'';clooooloooooooooooooooooooooooodo:';kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMM
 * MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd'':loo:..;looooooooooooooc,'':lodddkKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kxdo:;,,:lloollolc;'';cloooooollloooll:;,;coddddolcccc:;'',:clooodoooooooooc;'',:coooooooooooollooloooooooooloo:.,dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMM
 * MMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo''cll:'.,coooooooooooooc;'':lodocclkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kkxol:'';cllllloolc,'',:looooollloooooc;'';loodddlc:clll:;'',;:coooooooddddol;,'':cloooooooooolloloooolloooloo:''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMM
 * MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0l,:lol,.'coooloolcoooolc,.,coooc;;oOXNNNNNNNNNNNNNNNNNNNK0OOKXNXKOkO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kxxdoc,',:lllllllll:;''';cooolllllooool:,'':looddolc:cclllc;,'',;clooodddddool:;'',cllooloooooooooooooooloool:''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM
 * MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXklcloo:..;loooolc:clool:'.;lool;,;dKNNNNNNNNNNNNNX0OO00KK0koccox0Odc;:okKNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0Okxxdl:'',:lllllloool:,'',:loooollooddol:,',:lodddoolc:cloooc:,,'',:cloddooooooc;'',:llllloooooooooddooooloo:.'cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
 * MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKxllooc,.,coolol::cllol:'.;lool;':xKNNNNNNXK0O00K0xl:;;;:cldxxol:cdkOko:;lxKNNNNNNNNNNNNNNNNNNNNNNNNNNNKkdlllddl;'',,,,;clllccc:;'',;cooooooooooooc,',:loddddolcc:cldddlc:;,'',;:codoooool:,'';clllooooooooooooollol;.,lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
 * MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOolooo;..;looll:;:lllol;',cooc,'cOXNNXXXXKkdc:;::::::loddoc:;:ldxoccok0Od:;lOXNNNNNNNNNWNNNNNNNNNNNNNKOdlccloxxl;,'...',;,,'',;clc:,'',:looooloooool:'.';lodddddolc:clddodolc:;,''',:loooool:,'';cllooooooloodoololc;.,lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
 * MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkooddc,.,coollc;;cooolc,':ooc,'cOX0xocc:cccccloxxdoc:;;:lxOOkoccoxOkdodO0Oo;:dKNNNNNNNNNNNNNNNNNNNX0xlcoxxxdl:;:cc:,......,;:::::;,,,,,,,;cooooooooooc,'.',:loddddol:::lodddddool:;,'',;cllool:,.';clooooollodoooooc,.;d0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
 * MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkoloo:'.;loooc;,:lool::cclc:,':kXXOdllooooolclldk0XXKOxoc:cd0XKOxxOXXKOO0KKx:;o0XNNNNNNNNNNNNNNNX0xlcoxdl:::cllc:;,;clc;'.''''''''''',;,'.';cloddooloolc:,..,;loddddoc:;:loddddoodool:,''',:lool;'.':looodooooooooo:'.:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxllol:.':llol:,,codo:;coo:'..,d00kddooddddxkkO000KXNNNNNX0OOKNNNNXNNNNNNXNNXkccxKNNNNNNNNNNNNNNKxooxOOo:cxk00x:;cdkKKOo;'',,'..',,'...',,,,,;ccllllooolccc:;'.';codoodoc:;:loddoooododolc;,',:lllc,.':loooooooooool;.,lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkoooc,.,loolc,,:odo:,:oo:'..'lkd:;;::ccc:::loxKNNNNNNNNNNNNNNNNNWNNNNNNNNNNNXKOKNNNNNNNNNNNNNNKxoxKXX0kOKNNNXK0KXNNNKxccdO0kl,'',''..',,,,,'''',,,;loooc:::::;,'',:odddooc;;;coddoodoodddolc;,;:loc;'';cooooooooooc,.;dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xdoc'.,loll;';looc,,col'...:kK0O0KKXXXXXKKKKXNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX00XNNNNNNNNNNNNNNNNNNNXXXNNNX0kOOOko:;;:ccccc::cccccllooolc:;,;::;'',codddolc;,;loddddooolloool:::lol:'.,coooooc:cl:''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkdo:'.;lol:''cool:,;lo;...'l0NNNNNNNNNNNNNNNNNNNNNXXKXXKXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0O00KKKkl;,,,,,,''',:clll:;,,;:;,,;:codddoc;,;codddoc,;coddolcclol:'.,looll;,;:,.:ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxo:'.;llc'.,lool;':ol,...'cdddddddxxdddddoollllllc:::::::::::::::::cllodkOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXNNNNNNNNNNNNNNNNNNNNNNNXXKXXKOkkxdolllc:;;::;:cc:;,,;;,,',;codddl:,';coddl;'':oddooooool;.';lllc;',;',xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0dc'.;ll;..:lool:,:o:'''..',;:::::::ccccccccccllooodxxxxxxxxdxxxxdooolc:;;cx0XNNNNNNNNNNNNNNNNNX0xollllcccccllooooloooooddxxxxxxkkOOOOO0KKXNNNXK0Okxdolc:;,,;;;;,,;cc:;,;coddol;'':lool;'':looooooooc,.,clc:'.,:cxXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl'.;lc'.,cloodl;;,'.','.,o0XXXXKKK000OOOOOOO00KXXXXXXXKKKKXXNNWWWWWWNXOo;,lONNNNNNNNNNNNNNNKkl;;:cclllllllllllllllcc:::;;,,,,;;;;,,,;;:cldk0KXXKOxddolllc:;''',;cooooc,,;loddoc,';codo:'';lddoooool,.':cc,.'cx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx;':l:..;llodoc,','.,;'.c0WWWKxl::;;;,,,,,,,,,;;:::::;;,,;;:cllokKNWWWWXx;,o0NNNNNNNNNNNNNKo,;d0XXXXXXXXXXKKKKKKK0000OOkkkkkkOOOOOkkxdol:;,;cd0KOxolc;;:ccc:,'.,:loddol:',:loddl;',:odoc,';loddoooc,.';c;..:OXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo:cl;.'clodl;';dxc',:,.cOWWNk;.................................':xKWWWWKo,:kXNNNNNNNNNNNXd,;xKKkoccccccc::;;;;;;;;;;;;;;;;;:ccloxk0KXNNX0ko;,cdl;,''......'''',;coooodoc,';coddl;'':oooc,.;lddool:..,::'.;kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxoc,.,codl,'cOX0l',lc,;dXWNk;...................................,o0NWWNk;;xXNNNNNNNNNNNOc,o0Oc'.................................',;cdOXWWXx:,;ldocccc:,....';clllc::lodl;''codol;'':odo:.':lool:'.'::,.;kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxc'.,ldl,'l0NNKx;,ldc':kNNk;....................................'l0WMW0ook0OxooooodxkOd;,dKk;......................................':kXWWXd,,d0Oxollll:;'.,:looo:,';lool;'':lool;.,looc,.,col:'.,::,.;kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl,.,ll;':ONNNNKd:;cc,'c0Nk;.....................................;kNWWNOo:;;;:ccccc:;;,',dKO:.......................................'l0WWKo',okxo:;,;ccc;'.,coddl:,.;lool:'';ldoc'.:ool;.':llc::c:,.,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkc',cc',dKNNNNNXOdll:,;xX0c.....................................;xNWNOl;cdOKKXXXXK0Od:,,oKKo'.......................................;xNNOc'';:;,'.....''..',cdddoc'.;lool:'':lol,.;ldo;.':oolclc,.,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0l,''':ONNNNNNKOxol:',oXXd,....................................:OWNk:;dKNNNNNNNNNNNXOc,lKXx;.......................................,dXXd,':l:;,,,,'..'',,',codddo:''coool;.,coc,.;loc,.,ldoolc,.,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo,.':OXNNX0dc,',:c;'c0N0l'..................................;xXWXd,;xXNNNNNNNNNNNN0l,l0NO:.......................................,xXOc':kx:'.............'',;col,';oddo:'':l;.':l:'..,ldool;.,xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:.':dxdc,',cdOK0l';xNNk;.................................;xXWWKl':kXNNNNNNNNNNNNKo,cONXd,.....................................'cO0o';dKOl:;;;;,'':oddddl:;,'','.,lxdo:',c:,;c:,'...;lool;':kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,';:,.':oOXNNNXk;,oKWXd;...............................:kNWWXx;,oKNNNNNNNNNNNNNXx;:kNNO:.....................................;xKd,,oKNKOxl;,:lox0XNNNNNX0Odc,..':odoc:loooool:,..':clooldKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0l,''';d0NNNNNNNO:.:ONWXx:'...........................,l0NWWXx;,lOXNNNNNNNNNNNNNNO:,oKWXd,...................................,d0k;'c0NNKOdc,.'ckXNNNNNNNNNNNXOo:'.':ldxddxdol;'...,;;:d0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,.'lOXNNNNNNNNKd;,l0NWNOl,........................,lONWWN0o,,l0XNNNNNNNNNNNNNNNKo,:ONW0l'.................................,oOx;'cOXNNX0x:',:x0NNNNNNNNNNNNNNX0d;..;odlc:;,'',;,',:;;lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo,.;xKNNNNNNNNNNNXx:,cxKNNKxc,'...................,lONWWWXx;':xKNNNNNNNNNNNNNNNNNXk:,l0WN0o,..............................,lkOo,,l0NNNNNXKOookXNNNNNNNNNNNNNNNNNXkc'.',,'.',cll:'':l;,cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo,.:kXNNNNNNNNNNNNNXOo:;cd0XNX0xl;,''.........',:ld0NWWWWKo,,lOXNNNNNNNNNNNNNNNNNNNXx;,oKNWXOl:;'.......................';oOXOc';dKNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNOl,.',,';ldo:'';c:,,dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 * WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.;xXNNNNNNNNNNNNNNNNXOo:,;lx0KXXK0OkxdoooooxkOKXNWWWWX0d:,;o0NNNNNNNNNNNNNNNNNNNNNNKx:;lONWWNXKkoc;''................;okKX0d;':kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0l'..'':oo:'.,::''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0c.'oKNNNNNNNNNNNNNNNNNNNXKxl;,,;cldxkO00KK0KKKKKKKK0Oxo:;,:d0XNNNNNNNNNNNNNNNNNNNNNNNNXOdoloxKXNNWNXKOkdoc::;;;,,,,;:ld0XKko;,:d0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk:...':l:'.';;''l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.:kNNNNNNNNNNNNNNNNNNNNNNNX0kxol:;;;,;;;;,;;;;;;;;,,,:cdOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0xc;;cloxkO0KKKK0OOOOkkxxxxxxxoc;,;cx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXd,..,::'.';,.,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo''lKNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0Okxdddddddddddxxk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkdllc:;;;:::::::;;::::;;;;;clox0XNNWNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNN0c..,;'..''';xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo''oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0OOkkkkkkkkkkkkkkO00KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0l'.','...,lONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd,'cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO:.':c,',lkXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0c',o0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXd,.;odox0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0c',lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNX0Okkkxdl:;,'',,:ldxOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXx;.,dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKo,'ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk:,,'''',:coxxdl:,'',;coxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk;.'oKNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd,.:xKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0kxxxxxO0KXNNNNXKOxdl:,'':kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKd;.,oKNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:',:ok0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kxx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNKxc'.:xXNWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMM
 * MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxl;'';cdk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOo:'';o0NWWWNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
 * MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWNKkoc,',;coxk0KXNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNXKOkdl:'.,cxKNNNNWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMM
 * MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWNX0xoc;''',:coxO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kxxdooolllooooddxxxkkkkxxxddoooollc;''',:ldOXNWWWNWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
 * MMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNWWNWNNXKOxoc;,''',:codxk00KXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kdl:;,',;;:::;;;,,,''''''''''''''''',,,;:cldk0XNNWNWWWNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMM
 * MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNX0Oxoc:;,''',;:::ccllooddxxxxxxxxxxkO00KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKko:,'',:odkOKKXXXXKKK0OkkkOOkkkkkkkkkOO000KKXNNNWWWWWWWNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM
 * MMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXKOkxdolc::;;;,,''''''''''''''',;;;codkO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0dc;,;cdk0XNNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM
 * MMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWNNWWWWNNXXXXKK000Okkkkkxxxxxxxxddlc::;;;;:ldkOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNKxc;cx0XNNWWNNWWNWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMM
 * MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNWWWWNWWWNWWWWWWWNNNWWNWWWNWWWWNWNNXXK0kxdoc:;:lkKXNNNNNNNNNNNNNNNNNNNNNNNXOl,,l0NWWNWWWWNNWWWWWWWWWWWWWWNWWWWWWWNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMM
 * MMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWNWWNWWWWWWWWWWWWWWWWWWNNKkl,,cxKNNNNNNNNNNNNNNNNNNNNNXx;',dKNWWNWWWWWWWNWWWWWWWWWNWWWWWWWWWWNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMM
 * MMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:';dKNNNNNNNNNNNNNNNNNNNXx;.;xXWWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMM
 * MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx,.:kXNNNNNNNNNNNNNNNNNNOc.':oxOXWWNWWWWWWWWWNNNNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMM
 * MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0Oxo:'.,dXNNNNNNNNNNNNNNNNNNOc'':c:cd0XNWWWWWWWWNNNNNNWWWWWWWWWWWWNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMM
 * MMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNWNWWWWWWWWNNNXKKKKK00ko:''',;'.,oKNNNNNNNNNNNNNNNNNN0l':kKkc:codxOKXNNNWWWNNNNNNNNWWWWWWWWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMM
 * MMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNNNWNNNNKOkdolc:;,,,,,''''..:kk:.,dKNNNNNNNNNNNNNNNNNNO:'cOOc,ckOo;,;:cldxOKXNNNWWNNWWWWWWNNNNNNNNNNNNNNNNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMM
 * MMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNWWNKkoc;,;:clllc:,..;oxkx:,o0x,.;xXNNNNNNNNNNNNNNNNN0c,:xx:,cONWXOl'..,;;;:lxKNNNNNWWWWWWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMM
 * MMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOo;,;ldOKXNWWWNOc.'oXWNO:,okl'.:OXNNNNNNNNNNNNNNNXk:':xx:,c0NWWNk:.'ckKKOd:;cxKNNNNNWWWNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOo:',cxKWWMMMMMMWWKl''lKWWO:'::'.'cOXNNNNNNNNNNNX0kdl,'cxo;,l0WWWKd;.'l0WWWWN0d:;:dOKNNNNWWNNWNWWNNWWNNWWWWNNWWWWWWWWWWWWWWNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXko;,;cx0NWWMMMMMMMMMWXd'.:OWW0l,,cl:,,:coxxkkkkkkxoc;'.';dxl,;dKWWXkc'.;xKWWMWWMWNKxl;;:d0XNNWWNWNNNWNWWNNNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKkl;,,lkKNWMMMMMMMMMMMMMWNx;.;kNWNk:,o0KOdl:;;;,,,,,,,;::,'':c;,cONWW0l,.,l0NWWWMMWMMMWWN0dc;;lx0XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNX0kl,';lx0NWMWMMMMMMMMMMMMMMMWOc.'oKWWXx;,ckKXNXXK00OOOO000Od,...':xKWWXkc'.:kXWMMMMMMMMMMMWWWNXOo:;;lx00KXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0kxdlc;,';lkKNWMMMMMMMMMMMMMMMMMMMMWXx;.,oKWWXd,.,;codxkkkkkkxdoc:,'',cxKWWXkl,.,l0WWMMMMMMMMMMMMMMMMWWNKOo:,,;;:ccllodxkKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOd:,,,;:coxOKNWMWMMMMMMMMMMMMMMMMMMMMMMWXx;''ckXN0xdxdlc;;,,,,,,;;:lodkO0NWN0d:'.,ckXWMWWMMMMMMMMMMMMMMMMMMWWNKOkxdoollcc:;;:d0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0d:,,:dOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOo,',:oxkOXNNXK00OOO00KXXKkxk00kdc,.';oOXWMMWMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNXKkl;;cxKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd;':dOXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOo:,'.',:loddddddddodoo:''''''.',cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0d:,:xXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk:':xXWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXOo;'','''''''''''''''',:ccoxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWKd;,ckXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo,,o0WWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWN0kO00OOOOOOOOOOOkkOOKNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWWN0o;,l0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd,,oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMNOdkXWWWMMMMMMMWKxd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOc,:xXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;'lKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,lKWWMMMMMMMW0l;lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0o;,lOXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl':ONWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxlxXWWMMMMMMWNOdxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXOl;;o0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;'dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKk0NWWMWWWWXkokXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXx:,l0NWNWWWWWNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx:l0WWWWWNOc,:xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWNk;,oXWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWN0:'lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx;:kNWWN0o:lxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWKl'c0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNWWWWWNNNWWWWWWWWWWWWWWWWNNNk;,dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKolkXWN0c,oKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXx;,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNWNNNWNNWWWWWWWWWWWWWWWWNNWNO:'oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxcccll:,;xNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOl,,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNWNNNNNNNNNNNNNNNNNNNNNNNN0c'c0WWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0d:',:cclkNWWMMMMMMMMMMMMMMMMMMMWWNWMMMMMMMMMMMWNXNWMMMMMMMMMMMMMMWNNWWMMMMMMMMMWWXOl,,ckXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNXd;;xKNWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc,';ldkKNWWWMMMMMMMMMMMMMMWMWN0dco0NWWMMMMMWN0dc:dKWWMMMMMMMMWWN0dccxXWMMMMMMMWNkc,;lOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNXkc:cdOXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,':l:;dXWWWMMMMMMMMMMMMMWWNOc'..:kNWMMMWNX0d;..,oKNWWWWWWWWNKkl,.,lONWMMMWWWXkl,,o0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNWNNWNNXkl;;lx0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWN0d:'':c,':ox0NWMMMMMMMMMMMWNKx;..'oKNWWNKOdc;'..'',:xXWNX0kdol:;'..:kNWWWWNXKko:,;oONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNWWNNNNNNNNNNNNNNNNNNNX0xc;;cldkKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOdolcc::::clkXWMMMMMMWWWWKxc,....,o0KOoc,..';coxl,.'cdoc;'..',;;,..cOXKOxoc:;,;lxKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNX0xoc;,;cd0NWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNWWMMMMMMWNX0o,..,:;...;:,...;cdOXNNKl'.....':ldxO0KOc..,::;,,;cox0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkd:,;oOXNWWMMMMMMMMMMMMMMMMMMMMMWWMMMWWWWWWWWWWWWWWWWMMWWMWWMMMMWNOl;'..:xK0l'.....;oOKNWMMWXd,..';coxkOOxdlc;'.',:ldk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkl;;:lxO0K0OxdddddddddxxxxxxkkkkxdoolcccccloooooddxkOO0KXXNXX0o,...:d0XX0l'.',cxOKKKKKKKK0d:,,clc;,'',,;:loodkKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xoc;;;;,',;;;;;;;;;;;;;;;;;;;;;:ccllllcccccc::;;;,,,;;:::;,....';;:::;'..',;;;;,,,,,;;;,,',,,,;;:oO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxxk0KKKKKKKKKKKKKKKKKKKKKXNNNNNNNNNNNXXXKK00OkxxxxxxddddooooooooooodddxxddxxdddxxxxkO000KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 *
 */

package net.kunmc.lab.seihekizinrou.utils

import kotlinx.serialization.*
import kotlinx.serialization.json.*
import java.time.*
import java.time.format.*

fun Any.asJsonString() = Json.encodeToString(this)

fun String.asJsonElement() = Json.parseToJsonElement(this)
fun String.asJsonObject() = Json.parseToJsonElement(this).jsonObject
fun String.asJsonArray() = Json.parseToJsonElement(this).jsonArray

fun Any.asJsonElement() = asJsonString().asJsonElement()
fun Any.asJsonObject() = asJsonString().asJsonObject()
fun Any.asJsonArray() = asJsonString().asJsonArray()

inline fun <reified T> String.parseToObject() = Json.decodeFromString<T>(this)

fun JsonObject.getString(key: String) = get(key)!!.jsonPrimitive.content
fun JsonObject.getStringOrNull(key: String) = try {
    get(key)?.jsonPrimitive?.contentOrNull
} catch (e: Exception) {
    null
}

fun JsonObject.getInt(key: String) = get(key)!!.jsonPrimitive.int
fun JsonObject.getIntOrNull(key: String) = try {
    get(key)?.jsonPrimitive?.intOrNull
} catch (e: Exception) {
    null
}

fun JsonObject.getLong(key: String) = get(key)!!.jsonPrimitive.long
fun JsonObject.getLongOrNull(key: String) = try {
    get(key)?.jsonPrimitive?.longOrNull
} catch (e: Exception) {
    null
}

fun JsonObject.getDouble(key: String) = get(key)!!.jsonPrimitive.double
fun JsonObject.getDoubleOrNull(key: String) = try {
    get(key)?.jsonPrimitive?.doubleOrNull
} catch (e: Exception) {
    null
}

fun JsonObject.getFloat(key: String) = get(key)!!.jsonPrimitive.float
fun JsonObject.getFloatOrNull(key: String) = try {
    get(key)?.jsonPrimitive?.floatOrNull
} catch (e: Exception) {
    null
}

fun JsonObject.getBoolean(key: String) = get(key)!!.jsonPrimitive.boolean
fun JsonObject.getBooleanOrNull(key: String) = try {
    get(key)?.jsonPrimitive?.booleanOrNull
} catch (e: Exception) {
    null
}

fun JsonObject.getInstant(key: String) = get(key)!!
    .jsonPrimitive
    .content
    .let { DateTimeFormatter.ISO_DATE_TIME.parse(it) }
    .let { Instant.from(it) }

fun JsonObject.getInstantOrNull(key: String) = try {
    get(key)
        ?.jsonPrimitive
        ?.content
        ?.let { DateTimeFormatter.ISO_DATE_TIME.parse(it) }
        ?.let { Instant.from(it) }
} catch (e: Exception) {
    null
}

fun JsonObject.getPrimitive(key: String) = get(key)!!.jsonPrimitive
fun JsonObject.getPrimitiveOrNull(key: String) = try {
    get(key)?.jsonPrimitive
} catch (e: Exception) {
    null
}

fun JsonObject.getObject(key: String) = get(key)!!.jsonObject
fun JsonObject.getObjectOrNull(key: String) = try {
    get(key)?.jsonObject
} catch (e: Exception) {
    null
}

fun JsonObject.getArray(key: String) = get(key)!!.jsonArray
fun JsonObject.getArrayOrNull(key: String) = try {
    get(key)?.jsonArray
} catch (e: Exception) {
    null
}

fun JsonObject.getObjectArray(key: String) = get(key)!!.jsonArray.map { it.jsonObject }
fun JsonObject.getPrimitiveArray(key: String) = get(key)!!.jsonArray.map { it.jsonPrimitive }
fun JsonObject.getArrayArray(key: String) = get(key)!!.jsonArray.map { it.jsonArray }

fun JsonObject.getStringArray(key: String) = get(key)!!.jsonArray.map { it.jsonPrimitive.content }
fun JsonObject.getLongArray(key: String) = get(key)!!.jsonArray.map { it.jsonPrimitive.long }
fun JsonObject.getFloatArray(key: String) = get(key)!!.jsonArray.map { it.jsonPrimitive.float }
fun JsonObject.getDoubleArray(key: String) = get(key)!!.jsonArray.map { it.jsonPrimitive.double }
fun JsonObject.getBooleanArray(key: String) = get(key)!!.jsonArray.map { it.jsonPrimitive.boolean }

fun JsonObject.getObjectArrayOrNull(key: String) = try {
    get(key)?.jsonArray?.map { it.jsonObject }
} catch (e: Exception) {
    null
}

fun JsonObject.getPrimitiveArrayOrNull(key: String) = try {
    get(key)?.jsonArray?.map { it.jsonPrimitive }
} catch (e: Exception) {
    null
}

fun JsonObject.getArrayArrayOrNull(key: String) = try {
    get(key)?.jsonArray?.map { it.jsonArray }
} catch (e: Exception) {
    null
}

fun JsonObject.getStringArrayOrNull(key: String) = try {
    get(key)?.jsonArray?.map { it.jsonPrimitive.contentOrNull }
} catch (e: Exception) {
    null
}
fun JsonObject.getLongArrayOrNull(key: String) = try {
    get(key)?.jsonArray?.map { it.jsonPrimitive.longOrNull }
} catch (e: Exception) {
    null
}
fun JsonObject.getFloatArrayOrNull(key: String) = try {
    get(key)?.jsonArray?.map { it.jsonPrimitive.floatOrNull }
} catch (e: Exception) {
    null
}
fun JsonObject.getDoubleArrayOrNull(key: String) = try {
    get(key)?.jsonArray?.map { it.jsonPrimitive.doubleOrNull }
} catch (e: Exception) {
    null
}
fun JsonObject.getBooleanArrayOrNull(key: String) = try {
    get(key)?.jsonArray?.map { it.jsonPrimitive.booleanOrNull }
} catch (e: Exception) {
    null
}

fun JsonElement.getString(key: String) = jsonObject[key]!!.jsonPrimitive.content
fun JsonElement.getStringOrNull(key: String) = try {
    jsonObject[key]?.jsonPrimitive?.contentOrNull
} catch (e: Exception) {
    null
}

fun JsonElement.getInt(key: String) = jsonObject[key]!!.jsonPrimitive.int
fun JsonElement.getIntOrNull(key: String) = try {
    jsonObject[key]?.jsonPrimitive?.intOrNull
} catch (e: Exception) {
    null
}

fun JsonElement.getLong(key: String) = jsonObject[key]!!.jsonPrimitive.long
fun JsonElement.getLongOrNull(key: String) = try {
    jsonObject[key]?.jsonPrimitive?.longOrNull
} catch (e: Exception) {
    null
}

fun JsonElement.getDouble(key: String) = jsonObject[key]!!.jsonPrimitive.double
fun JsonElement.getDoubleOrNull(key: String) = try {
    jsonObject[key]?.jsonPrimitive?.doubleOrNull
} catch (e: Exception) {
    null
}

fun JsonElement.getFloat(key: String) = jsonObject[key]!!.jsonPrimitive.float
fun JsonElement.getFloatOrNull(key: String) = try {
    jsonObject[key]?.jsonPrimitive?.floatOrNull
} catch (e: Exception) {
    null
}

fun JsonElement.getBoolean(key: String) = jsonObject[key]!!.jsonPrimitive.boolean
fun JsonElement.getBooleanOrNull(key: String) = try {
    jsonObject[key]?.jsonPrimitive?.booleanOrNull
} catch (e: Exception) {
    null
}

fun JsonElement.getPrimitive(key: String) = jsonObject[key]!!.jsonPrimitive
fun JsonElement.getPrimitiveOrNull(key: String) = try {
    jsonObject[key]?.jsonPrimitive
} catch (e: Exception) {
    null
}

fun JsonElement.getObject(key: String) = jsonObject[key]!!.jsonObject
fun JsonElement.getObjectOrNull(key: String) = try {
    jsonObject[key]?.jsonObject
} catch (e: Exception) {
    null
}

fun JsonElement.getArray(key: String) = jsonObject[key]!!.jsonArray
fun JsonElement.getArrayOrNull(key: String) = try {
    jsonObject[key]?.jsonArray
} catch (e: Exception) {
    null
}

fun JsonElement.getObjectArray(key: String) = jsonObject[key]!!.jsonArray.map { it.jsonObject }
fun JsonElement.getPrimitiveArray(key: String) = jsonObject[key]!!.jsonArray.map { it.jsonPrimitive }
fun JsonElement.getArrayArray(key: String) = jsonObject[key]!!.jsonArray.map { it.jsonArray }

fun JsonElement.getObjectArrayOrNull(key: String) = try {
    jsonObject[key]?.jsonArray?.map { it.jsonObject }
} catch (e: Exception) {
    null
}

fun JsonElement.getPrimitiveArrayOrNull(key: String) = try {
    jsonObject[key]?.jsonArray?.map { it.jsonPrimitive }
} catch (e: Exception) {
    null
}

fun JsonElement.getArrayArrayOrNull(key: String) = try {
    jsonObject[key]?.jsonArray?.map { it.jsonArray }
} catch (e: Exception) {
    null
}